Battle-Modders/mod-reforged

ui/mods/mod_reforged/css_hooks/screens/tooltip/modules/tactical_screen_topbar/topbar_event_log_module.css, ui/mods/mod_reforged/js_hooks/screens/tooltip/modules/tactical_screen_topbar/topbar_event_log_module.js
This adds a line of code from Leonions original solution which I forgot. 
Now all necessary widths are correctly adjusted retroactively after the vanilla function ran through.
=> fix: correctly use dynamic width instead of a static one for combat log

scripts/skills/special/rf_reach.nut
Without this fix, the following bug happens: https://discord.com/channels/1006908336991645757/1074043332587696258/1074043332587696258
We need to switch the `CurrentProperties` with `_properties` because effects such as `stunned_effect`, when added, change the `IsStunned` attribute to true in `_properties`, but it isn't yet updated for `CurrentProperties` because `_properties` becomes `CurrentProperties` at the end of the current skill_container update. This causes `hasZoneOfControl` to return true because it uses `CurrentProperties` to check for `IsStunned`.
This switcheroo is better than checking for `_properties.IsStunned` because we want to use hasZoneOfControl to be able to check for all (potentially new modded) conditions which may remove zone of control. **Secondly**, without the …
=> fix: switch CurrentProperties with _properties before hasZoneOfControl

scripts/skills/effects/rf_encumbrance_effect.nut
This _is_ how the encumbrance mechanic was originally conceptualized to work. Currently, the way vanilla works is that Fatigue Recovery is only relevant until you reach maximum fatigue. At that point, you always regain 15 Fatigue. This makes traits such as Asthmatic, and injuries which affect Fatigue Recovery basically irrelevant at that stage. It also makes it so that the Encumbrance mechanic doesn't work as intended.
To change the complete mechanic so that Fatigue Recovery is always used at Max Fatigue instead of a minimum of 15 would require overwriting actor.nut `onTurnStart` function or doing an ugly switcheroo on it as it touches many things. So, instead of doing that, this PR makes it so that only the "Encumbrance" mechanic overrides the min. 15 Fatigue recovery mechanic, which …
=> refactor: change encumbrance to increase fatigue at turn start

mod_reforged/hooks/entity/tactical/enemies/schrat.nut, mod_reforged/hooks/entity/tactical/enemies/schrat_small.nut, mod_reforged/hooks/skills/racial/schrat_racial.nut, scripts/skills/effects/rf_sapling_harvest_effect.nut
In return this will extract the Sapling-Spawn effect out of the Schrat-Racial and into its own new effect that is only given to Schrats for now.
Screenshot on how it looks ingame:
=> feat: give Saplings the Schrat-Racial effect

mod_reforged/hooks/config/tactical_entity_common.nut, mod_reforged/hooks/skills/items/firearms_resistance_skill.nut, mod_reforged/hooks/skills/racial/alp_racial.nut, mod_reforged/hooks/skills/racial/golem_racial.nut, mod_reforged/hooks/skills/racial/schrat_racial.nut, mod_reforged/hooks/skills/racial/serpent_racial.nut, mod_reforged/hooks/skills/racial/skeleton_racial.nut
Vanilla does racial damage reductions and increases hard-coded. This also causes several mistakes where sometimes a specific attack was missing causing that type of damage to deal full damage.
Reforged already did a first rework pass on these racial effects by mimicing them via the DamageType system.
**Overview of the changes:**
This PR tries to simplify those values so they are more presentable to players and understandable for devs.
Burning Ground no longer has inherit mutlipliers for different entity-types. Instead it uses the MSU damage type system and leaves the multipliers to the individual entities.
All races that are resistance to piercing attacks now all have 
- a 66% (or 75% in case of Schrat) damage reduction against ranged piercing (arrows damage is buffed, a few other random …
=> feat: streamline and simplify racial damage reductions

mod_reforged/hooks/ai/tactical/behavior.nut
Mortars are not meant to be killed but in Vanilla, But AI still targets them. This is frustrating when allies waste their ranged attacks on mortars or your dogs get hung up on them instead of pinning down the engineers or fleeing enemies.
This PR reduces those instances to a minimum by tanking the value of mortars.
This is an exact copy from an AI-Fix-Collection mod of mine and I ran this in a longer campaign without issues. Though I can't remember this exact case of AI-Targeting was actually fixed.
=> fix: prevent AI from targeting mortars

mod_reforged/hooks/skills/racial/ghost_racial.nut, mod_reforged/hooks/skills/racial/goblin_ambusher_racial.nut, mod_reforged/hooks/skills/racial/goblin_shaman_racial.nut, mod_reforged/hooks/skills/racial/lindwurm_racial.nut, mod_reforged/hooks/skills/racial/serpent_racial.nut, mod_reforged/hooks/skills/racial/spider_racial.nut, mod_reforged/hooks/skills/racial/vampire_racial.nut
There is currently no reason that some of those racial effects randomly had the type 'Perk'. This currently causes issues with our tooltips trying to display those. Also it will cause the Oblivion Potion to remove those racial effects if they are ever to appear on "brothers".
**Important:** This PR requires MSU functions which are not yet in MSU. Enduriel said that he wants to get them in ASAP
=> refactor: remove the Type 'Perk' from all racial effects

mod_reforged/hooks/skills/effects/nine_lives_effect.nut, mod_reforged/hooks/skills/perks/perk_nine_lives.nut
Currently there is no indicator on an entity with Nine-Lives that tells you whether it still has Cheat-Death available. The only way to know is trying to remember whenever you see it being procced.
This PR solves that problem by always displaying the nine-lives mini-icon on top of entities while it is available.
As a side-effect the mini-icon is now removed from the second half of this perk, the one turn stat-buff. But this is a small price to pay for this QoL improvement. Also once we get a variation of that mini-icon we can re-implement that for the second half and have the best of both worlds.
This PR also improves the tweakability of Nine-Lives slightly with the `onProc` function.
I mostly copied the approach that Midas implemented in Legends for this 7 months ago.
**Important:** This …
=> feat: show mini-icon for nine-lives while cheat-death effect available

mod_reforged/hooks/config/tip_of_the_day.nut
Remove 11 existing vanilla tips of the day
Add 5 new tips of the day
I tested it ingame and could confirm it removing them correctly and was able to see one of my new tips after a few tries.
=> feat: add a few new tips of the day

scripts/skills/special/rf_polearm_adjacency.nut
Changes:
- Change: Ignore the first two adjacent allies for the adjacency malus.
- Change: Add Name, Description and nested tooltip hyperlinks.
- Fix: Remove the condition for being the active entity.
- Fix: onQueryTooltip using this.m.MalusPerAlly instead of MalusPerEnemy for enemies
Code improvements:
- New isEnabledForSkill function to centralize conditions to check for skills.
- New getMalusForSkill function to get the malus instead of storing in a this.m.TotalMalus variable.
- Iterate over adjacent tiles instead of all actors on the map.
=> Polearm adjacency tweak

mod_reforged/config/text/text.nut, mod_reforged/hooks/contracts/contract.nut, mod_reforged/hooks/contracts/contracts/deliver_item_contract.nut, mod_reforged/hooks/contracts/contracts/escort_caravan_contract.nut, mod_reforged/hooks/contracts/contracts/return_item_contract.nut, mod_reforged/hooks/msu.nut
- Deliver Item and Caravan Contracts now display their estimated time in days + hours
- Return Item Contract now displays the original payout during a CounterOffer event
- Return Item Contract thieves are a bit easier to catch should they choose to run (10% slower)
- Contracts with a settlement as their destination will now try to display an image of that during the contract dialog
=> feat: improve quality of life of a few vanilla contracts

mod_reforged/hooks/items/shields/special/craftable_schrat_shield.nut, mod_reforged/hooks/items/weapons/barbarians/axehammer.nut, mod_reforged/hooks/items/weapons/barbarians/crude_axe.nut, mod_reforged/hooks/items/weapons/barbarians/heavy_rusty_axe.nut, mod_reforged/hooks/items/weapons/bardiche.nut, mod_reforged/hooks/items/weapons/fighting_axe.nut, mod_reforged/hooks/items/weapons/greataxe.nut, mod_reforged/hooks/items/weapons/greenskins/orc_axe.nut, mod_reforged/hooks/items/weapons/greenskins/orc_axe_2h.nut, mod_reforged/hooks/items/weapons/hand_axe.nut, mod_reforged/hooks/items/weapons/hatchet.nut, mod_reforged/hooks/items/weapons/longaxe.nut, mod_reforged/hooks/items/weapons/throwing_spear.nut, scripts/items/weapons/rf_battle_axe.nut
This improves the reliability of shields across the board especially Kite Shields and above. The change to the Living Tree Shield ensures that it isn't destroyed by a single hit from a Mansplitter with Axe Mastery and Shield Expert.
Weapons:
- axehammer: 22 to 12
- crude_axe: 22 to 16
- heavy_rusty_axe: 46 to 40
- bardiche: 42 to 32
- fighting_axe: 26 to 18
- greataxe: 46 to 40
- orc_axe: 42 to 22
- orc_axe_2h: 68 to 54
- hand_axe: 22 to 12
- hatchet: 14 to 10
- longaxe: 30 to 32
- throwing_spear: 48 to 40
- rf_battle_axe: 28 to 26
Shields:
- craftable_schrat_shield: 40 to 42
=> refactor: rebalance shield damage of weapons and shield durability

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/entity/tactical/enemies/orc_warrior.nut, mod_reforged/hooks/entity/tactical/enemies/sand_golem.nut, mod_reforged/hooks/entity/tactical/enemies/schrat.nut, mod_reforged/hooks/entity/tactical/enemies/trickster_god.nut, mod_reforged/hooks/entity/tactical/enemies/unhold.nut, mod_reforged/hooks/entity/tactical/enemies/unhold_bog.nut, mod_reforged/hooks/entity/tactical/enemies/unhold_frost.nut, mod_reforged/hooks/entity/tactical/humans/hedge_knight.nut, mod_reforged/hooks/entity/tactical/humans/officer.nut, scripts/mods/mod_reforged/perk_groups/pg_rf_axe.nut, scripts/mods/mod_reforged/perk_groups/pg_rf_hammer.nut, scripts/mods/mod_reforged/perk_groups/pg_rf_sword.nut, scripts/mods/mod_reforged/perk_groups/pg_rf_wildling.nut, scripts/skills/effects/rf_fluid_weapon_effect.nut, scripts/skills/perks/perk_rf_cull.nut, scripts/skills/perks/perk_rf_deep_impact.nut, scripts/skills/perks/perk_rf_tempo.nut
The changes in this PR are based on my 145 days play test, and also based on discussions with players in the public server. The intention is to reduce perks that are considered non-competitive with other options at their tiers. Also, to reduce the overall number of "mediocre" perks. This is achieved as follows:
- Bestial Vigor, moved from tier 5 to tier 2. Ideally this should be tier 1. It's basically an improved Recover, which is available to the Wildling only and is one use per combat. But on tier 1 we have Pathfinder, so it goes on tier 2 for now.
- Savage Strength is a strong perk. It moves from tier 3 to tier 5.
- Heft is a no-brainer perk for axes right now. So it has been removed and a lite version of its bonus (10% instead of 30%) has been baked into the Cull perk.
- Internal …
=> Perks rebalance

mod_reforged/hooks/config/strings.nut, scripts/skills/actives/rf_swordmaster_active_abstract.nut, scripts/skills/effects/rf_swordmasters_finesse_effect.nut, scripts/skills/perks/perk_rf_swordmaster_abstract.nut, scripts/skills/perks/perk_rf_swordmaster_metzger.nut
- Allow hybrid swords to be used for Swordmaster perks.
- Allow Sword/Cleaver hybrids to be a valid weapon for Metzger (in addition to southern swords).
If we run into particular issues where the perks feel weird with certain weapons, we can then exclude them as necessary.
=> Swordmaster perks hybrid swords

scripts/skills/actives/rf_en_garde_toggle_skill.nut
@Darxo Let me know if you can think of a better solution, otherwise we can go with this.
EDIT: Uberbagel playtested it and it works. So unless there is a better solution, we can implement this.
=> fix: add hook on rebuke onTurnStart to remove itself

mod_reforged/config/talent_multipliers.nut, scripts/mods/mod_reforged/perk_groups/pg_rf_ranged.nut
- At least one ranged weapon perk group must be present (bow, crossbow or throwing). Otherwise the ranged perk group cannot be rolled.
- For each ranged weapon perk group present, the multiplier increases by 1. 
- For each talent star in Ranged Skill the multiplier increases by 1.
=> refactor: add dynamic self multiplier for ranged perk group

mod_reforged/hooks/skills/perks/perk_anticipation.nut
Fix Anticipation to work like it was initially envisioned to grant no natural damage reduction against adjacent entities.
=> refactor(balance): reduce damage reduction of Anticipation by 10%

mod_reforged/hooks/config/strings.nut, scripts/skills/actives/rf_swordmaster_kick_skill.nut, scripts/skills/actives/rf_swordmaster_push_through_skill.nut, scripts/skills/actives/rf_swordmaster_tackle_skill.nut
- Set AP cost to 6 and Fatigue cost to 15.
- Always stagger the target.
- Perform a free attack.
- If the attack is successful: Kick moves the target back a tile, Push Through moves the target back and you move into their place, Tackle exchanges positions.
I had a discussion with some players. Apparently no one picks Grappler because it is currently very weak compared to the other swordmaster perks. With these changes, it's now more competitive - although probably still overshadowed by a couple other perks. But seems like a step in the right direction.
=> refactor: rework swordmaster grappler skills

mod_reforged/actor_tooltip_functions.nut, mod_reforged/hooks/ui/screens/tactical/modules/turn_sequence_bar/turn_sequence_bar.nut
Currently permanent Injuries are not shown on combat tooltips or above the turn sequence bar overlay (left side by the stats)
This is because those only query and show:
- ::Const.SkillType.StatusEffect
- ::Const.SkillType.Perk (For Combat Tooltips only)
But permanent injuries are, unlike normal injuries, not of type `::Const.SkillType.StatusEffect`.
As a result you will sometimes wonder why your some fodder brother is so weak/slow even though they don't have any statuseffects.
This is where permanent injuries will now are displayed after this fix, which wasn't the case before:
=> fix: hidden permanent injuries

mod_reforged/config/ai.nut, mod_reforged/hooks/ai/tactical/agent.nut, mod_reforged/hooks/ai/tactical/behaviors/ai_defend_knock_back.nut, mod_reforged/hooks/skills/actives/decapitate_skill.nut, mod_reforged/hooks/skills/actives/gash_skill.nut, mod_reforged/hooks/skills/actives/puncture.nut, mod_reforged/hooks/skills/actives/riposte.nut, scripts/skills/actives/rf_net_pull_skill.nut
Previous MSU build automatically added `AIBehaviorID` to all vanilla skills. This meant that the behavior for said skills was also automatically added to any entity who got the skill. This resulted in Zombies using stuff like Gash, Decapitate, Puncture etc. 
The recent MSU build fixed this by no longer adding `AIBehaviorID` to skills automatically. This means mods now have to add them manually, but then also have to care about which agents they don't want those behaviors to be added to.
=> Ai behaviors assignment following msu update

mod_reforged/hooks/entity/tactical/player.nut
This leads to a narrower range of RNG compared to randomizing all the level-ups.
This PR should be used instead of #176. If it still feels bad in-game, then we can use the other one.
=> refactor: set half of the levelups with 2-stars to be -1 or +1

mod_reforged/hooks/entity/tactical/player.nut
In vanilla the `::Const.LevelXP` array has a length of 33 and the `addXP` function does an early return if the character's level is equal to or greater than its length. This means that characters stop gaining XP at level 33. In this hook we expand the array as necessary when the level value reaches its length. The calculation used for adding the XP requirement is taken from the vanilla calculation.
=> feat: allow leveling up indefinitely

mod_reforged/config/config.nut, mod_reforged/hooks/entity/tactical/actor.nut, mod_reforged/hooks/entity/tactical/player.nut, mod_reforged/hooks/skills/skill_container.nut
I have left many `logInfo` in the code for now so you can test the PR on your own if you want. These should be removed before merging.
- XP is now awarded based on the percentage of total damage dealt to an entity.
- Loot should now drop if the player faction did at least 50% of damage. But this is implemented in a hacky way, and we should really think this through if we want to do it like this, or if there is a better solution.
=> Feat damage based xp system

mod_reforged/config/config.nut, mod_reforged/hooks/entity/world/location.nut, mod_reforged/hooks/entity/world/settlement.nut
This change was meant to affect all locations but during my tests only settlements were affected. But that is not even bad because the Settlements were the most important ones to fix anyways.
I haven't tested this exact implementation yet. 
The test I showed you didn't utilize a central `adjustBannerOffset` and wasn't based on Modern Hooks.
=> refactor: add an offset for location banner to prevent an overlap

mod_reforged/hooks/ai/tactical/behaviors/ai_line_breaker.nut, scripts/ai/tactical/behaviors/ai_rf_hold_steady.nut, scripts/ai/tactical/behaviors/ai_rf_onslaught.nut
The previous ai package for these skills wasn't even working properly due to some logical issues in the algorithm. I've tested this new implementation and it works. We can tweak the AI over time more based on feedback.
It now uses the number of enemies adjacent to relevant allies and checks the hit-chance of allies vs enemies to determine whether to hold steady or to onslaught. Basically if enemies have a much greater hitchance than allies, then usage of Hold Steady is preferred, and if allies have hitchance close to enemy hit-chance or better than enemy hitchance, then usage of Onslaught is preferred. In both cases at least 3 relevant allies are required, otherwise the skills won't be triggered.
=> Ai tweaks onslaught holdsteady

mod_reforged/hooks/ui/screens/tooltip/tooltip_events.nut
Fixes [this](https://discord.com/channels/1006908336991645757/1163905659834732594) bug.
=> fix: add veteran perks and hyperlinks to Experience and Level tooltips

mod_reforged/hooks/skills/actives/fling_back_skill.nut, mod_reforged/hooks/skills/actives/line_breaker.nut
This bandaid accounts for the mod Swifter that has faster combat speed
I playtested the Line Breaker delay alot and after that I didn't have any issues with my brothers or orcs not moving into the line-broken tile. Though I was also never playing on the highest speed. Only 3/3.5
Fling Back had the same issue. Though I haven't fought enough unholds to remember whether the issue was fixed
=> fix: add 100ms to onFollow of fling back and line breaker

mod_reforged/hooks/items/weapons/oriental/nomad_sling.nut, mod_reforged/hooks/items/weapons/staff_sling.nut
This is a fix because of how the hook in MSU works that breaks Categories when using addWeaponType. Once the MSU behavior is fixed, we can revert to using addWeaponType.
=> fix: use setWeaponType instead of addWeaponType

mod_reforged/hooks/skills/backgrounds/character_background.nut
Remove unintended tooltip when in Barber, Training hall or Temple.
This tooltip used to be misused by us so we can display advanced information. But that is no longer needed as we display that information on additional tabs on the right side of the hiring screen.
=> fix: projected attributes being shown on brothers about to be hired

mod_reforged/hooks/skills/backgrounds/barbarian_background.nut, mod_reforged/hooks/skills/backgrounds/eunuch_background.nut
In vanilla these three backgrounds have the same chance of spawning with a beard than anyone else: 60%.
I believe it is more thematic if that chance is adjusted for these backgrounds
=> refactor: customize beardchance for eunuch, wildman and barbarian

ui/mods/mod_reforged/js_hooks/screens/tooltip/modules/tooltip_module.js
I put the css classes to change in a dict so it's neater
=> fix: tooltips potentially overlapping the cursor by moving them to the left or right in that case

mod_reforged/hooks/events/events/dlc4/kings_guard_1_event.nut, mod_reforged/hooks/events/events/dlc4/kings_guard_2_event.nut, mod_reforged/hooks/skills/backgrounds/kings_guard_background.nut
This PR does 3 things:
- Remove Promised Potential perk from the cripple version of Kingsguard.
- Properly add the perk tree of the Kingsguard background to the perk tree of the cripple when he evolves into the kingsguard. (An update on the Dynamic Perks Framework side ensures that 13 columns are respected, overflown perks are moved into other tiers).
- Fix a typo in perk group id in kings_guard_background.
=> refactor: remove promised potential from kingsguard cripple

mod_reforged/hooks/entity/world/location.nut, mod_reforged/hooks/entity/world/party.nut
This is a helpful tool during the beta test to allow us to better judge the feedback about the spawns. Note: Right now it shows the strength even for parties for whom the troop composition is unknown - this is intended because we want to know the party strength for our data and feedback purposes even if the target party composition is unknown before attacking them.
=> feat: add player and target party strength to party and location tooltip

mod_reforged/hooks/items/weapons/wooden_flail.nut
As discussed yesterday, this PR will buff the minimum and maximum damage of the wooden flail by +5 to bring it in line with the wooden stick and the knife.
=> refactor(balance): increase damage of wooden flail

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_cull.nut
This will prevent all kinds of weird interactions where non-damaging attacks were able to procc cull.
Not only can that be a balancing concern with cheap attacks but it can also lead to crashes with skills that never expect the target to suddenly be dead after being used on it
=> refactor: require atleast 1 hitpoint damage for cull to trigger

mod_reforged/hooks/skills/actives/throw_net.nut
In vanilla you can throw the net on such targets but it will "miss" i.e. you will lose the net and the target won't get netted. I suggest we make the net unusable on such targets.
=> refactor: make throw net unusable on root immune targets

scripts/skills/actives/rf_arrow_to_the_knee_skill.nut, scripts/skills/effects/rf_arrow_to_the_knee_debuff_effect.nut
- The active skill now inherits from quick_shot. This ensures that many effects which weren't properly accounted for in the original implementation but are implemented in vanilla e.g. _properties.IsSharpshooter are now automatically applied. Also cleans up the code quite a bit.
- Reduced AP cost to 4.
- Now applies Staggered effect as well.
- Removed defense malus from arrow to the knee debuff.
=> refactor: rework arrow to the knee skill and effect

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_dismantle.nut
- Add requirement for Hammer weapon
- Add requirement for Blunt damage type
- Add requirement to hit an actual armor piece
- Add requirement to do at least some armor damage
- Add double the stacks for two-handed hammer
- Clean up conditions in if statement in onTargetHit
=> refactor: rework dismantle

scripts/skills/effects/rf_mentors_presence_effect.nut, scripts/skills/perks/perk_rf_mentor.nut
- As mentor: Don't gain bonuses from student's death when you are fleeing or stunned
- As student: Don't gain morale bonus at turn start when mentor is fleeing
=> Mentors presence tweaks

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_bear_down.nut
- Require mace
- Reduce bonus headshot chance from 20% to 15%
- Remove melee skill bonus and grant injury threshold reduction instead
=> refactor: rework bear down

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_kingfisher.nut
- Use the throw net skill. So can benefit from perks which enhance throw net skill.
- Properly disable swapping the net, the previous implementation could have been circumvented by other perks that grant reduced AP offhand swapping.
- Lose the net when moving more than 1 tile away from the netted target.
=> Rework kingfisher to clean up code and grant +2 Reach with usable net

mod_reforged/hooks/factions/faction_manager.nut
At some point this faction was "disabled" or just skipped to ever appear ingame randomly. Their custom art still exists but is unused ever since.
Instead of rewriting the whole vanilla function this hook switcheroos out the ::Math.rand function very briefly during the generation of a new map only.
I tested it ingame and after several tries, the castle faction finally appeared.
=> refactor: allow castle-helmet noble helmet to appear again

mod_reforged/hooks/config/strings.nut, scripts/skills/actives/rf_net_pull_skill.nut, scripts/skills/perks/perk_rf_angler.nut
- Increase AP cost of Break Free skill on target by 1.5
- Apply Stagger via Net Pull
- Call useForFree instead of onUse in Net Pull to trigger an actual skill use function call relevant for next point:
- Allow angler to work with free usages of Throw Net (e.g. via net pull)
Also includes a few bug-fix commits.
=> Rework angler perk and net pull skill

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_fresh_and_furious.nut
Now checks fatigue against the threshold at the start of a turn. So going above the threshold during a turn will not disable it (i.e. require recover to re-activate it) as long as you can start your next turn below the threshold.
=> refactor: require recover to re-enable fresh and furious

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/special/double_grip.nut, scripts/skills/actives/rf_en_garde_toggle_skill.nut
- Allow Double Grip bonus for southern swords with offhand item with less than 10 weight.
- Allow triggering even after movement but in this case build 15 Fatigue.
- Fix: prevent en garde from triggering when disarmed.
=> refactor: rework en garde perk

mod_reforged/hooks/config/tip_of_the_day.nut, mod_reforged/hooks/states/world_state.nut
This is done by replicating the important conditions for this kind of click. 
At the very end, we skip checking for whether player and target are on the same tile and also check for the increased range
=> feat: increase town interaction range while on a caravan mission

mod_reforged/hooks/skills/special/double_grip.nut
So that it runs before all perks and items so that any effects applied by it during an attack are then taken into consideration for all subsequently updated skills/items in their functions such as onTargetHit.
=> refactor: set SkillOrder of double grip to First

mod_reforged/hooks/entity/tactical/actor.nut
The changes from the Reforged-added positive and negative morale check related fields were being added to the CurrentProperties before the morale check, but were not being reverted after the morale check.
=> fix: properly revert the changes to morale check bravery fields

mod_reforged/hooks/entity/tactical/actor.nut, scripts/skills/special/rf_first_turn_initiative.nut
During the first turn of every combat every characters Action Points are slightly modified depending on their current Initiative at that time.
Possible Todo: 
- Maybe get a unique Icon for this effect. Currently it uses the Impatient-Trait Icon
- Move the two "public" variables over to the `Characters.nut` so that other skills like perks can influence these values
=> feat: implement first turn initiative AP bonus

mod_reforged/hooks/entity/tactical/actor.nut, mod_reforged/hooks/skills/skill_container.nut
- Fix the issue where we switch the `_killer` in our hook on actor `onDeath` function causing MSU hook on `onDeath` to receive this wrong killer.
- Clean up the switching of the `_killer` by setting it to `null` instead of to a bro, because this is enough to drop loot for the player.
=> Fix pass correct killer to msu ondeath events

scripts/mods/mod_reforged/dynamic_spawns/units/barbarian_units.nut, scripts/mods/mod_reforged/dynamic_spawns/units/beast_units.nut, scripts/mods/mod_reforged/dynamic_spawns/units/southern_units.nut, scripts/mods/mod_reforged/dynamic_spawns/units/undead_units.nut, scripts/mods/mod_reforged/dynamic_spawns/units/zombie_units.nut
Dynamic Spawns Framework 0.3.0 adds the cost of the spawned party into the cost of the unit when subtracting its worth from the top party's resources. So we add a check to not use resources from the top party, and remove the manual addition of the extra cost from the unit with the subparty.
=> fix: resource usage and cost calculation for units with subparties

mod_reforged/config/items.nut, mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/perks/perk_duelist.nut, mod_reforged/hooks/skills/skill.nut
- Remove requirement for base AP cost of skill to be <= 4.
- Add requirement for being the skill of a weapon whose primary attack has a Base AP cost of <=4 (this means it no longer work with unarmed attacks - this is acceptable imo because this keeps the code a lot cleaner).
- Still requires the skill to be melee with a base maximum range of 1 tile.
=> Rework duelist validity

mod_reforged/hooks/crafting/blueprints/acid_flask_blueprint.nut, mod_reforged/hooks/crafting/blueprints/daze_bomb_blueprint.nut, mod_reforged/hooks/crafting/blueprints/fire_bomb_blueprint.nut, mod_reforged/hooks/crafting/blueprints/smoke_bomb_blueprint.nut, mod_reforged/hooks/items/tools/acid_flask_item.nut, mod_reforged/hooks/items/tools/daze_bomb_item.nut, mod_reforged/hooks/items/tools/fire_bomb_item.nut, mod_reforged/hooks/items/tools/smoke_bomb_item.nut
This primarily affects purchasing these items from the Alchemist buildings in the south. This change is based on player feedback as well as my own experience, having never bought those items at the Alchemist as they are far too expensive. Consider that the stated value in the file is still modified by buyprice modifiers of the faction/settlement.
=> feat: double crafting output of throwables and lower value by about 30%

mod_reforged/hooks/skills/actives/cleave.nut, mod_reforged/hooks/skills/effects/bleeding_effect.nut, mod_reforged/hooks/skills/racial/unhold_racial.nut, mod_reforged/hooks/skills/traits/bleeder_trait.nut
- Bleeding does not expire during battle. Stacks within the same effect instead of multiple instances. Applies 1 damage per turn per stack. Reduces Initiative and Resolve by 5% per stack up to maximum of 50%.
- Bleeder trait doubles the damage received from bleeding instead of the vanilla effect of longer bleeding.
- Adjust cleave skill tooltip for reworked bleed effect
=> Feat bleed effect rework

mod_reforged/hooks/entity/tactical/actor.nut
Completely overwrites the vanilla actor functions of `onOtherActorDeath` and `onOtherActorFleeing`. The logic is the same as the vanilla functions except:
- The negative morale check from dying or fleeing allies is now scaled with the ratio of the ally's XP value to my XP value. This means that a weaker ally dying will trigger a weaker morale check for more powerful entities (e.g. Thug dying in front of a Bandit Leader. But a Leader dying or fleeing will trigger an even stronger than before morale check for Thug).
- The positive morale check from an enemy dying is only triggered if the killer is null or is allied to my faction.
EDIT: In my opinion this should be a `feat:` commit so I'll update the commit message to reflect that before merging.
=> refactor: add xp ratio scaling to dying and fleeing ally morale check

scripts/skills/actives/rf_en_garde_toggle_skill.nut, scripts/skills/perks/perk_rf_combo.nut, scripts/skills/perks/perk_rf_fresh_and_furious.nut, scripts/skills/perks/perk_rf_momentum.nut, scripts/skills/perks/perk_rf_vanquisher.nut, scripts/skills/perks/perk_rf_vigorous_assault.nut
This is based on the [new affordability system](https://github.com/MSUTeam/MSU/pull/346) I am implementing in MSU.
EDIT: 2024-05-10
I've created an [even better](https://github.com/MSUTeam/MSU/pull/354) affordability system in MSU so the PR has been updated to account for that.
=> refactor: change to use new msu affordability preview system

mod_reforged/hooks/entity/tactical/actor.nut, mod_reforged/hooks/skills/skill_container.nut, scripts/!mods_preload/mod_reforged.nut
After having merged #369 I realized that the part about passing the correct killer to MSU `skill_container` functions was unnecessary because MSU hooks the actor `onDeath` function _after_ Reforged. So I'm reverting that. But this also gave me the idea that we should do this changing of `_killer` as early as possible i.e. before most other mods would `hookTree` the `onDeath` of actor, so I have moved it to an Early bucket hook. This should make most mods safe from breaking due to our modification of `_killer`.
We don't have a clean setup for Early bucket hooks right now. The "proper" way would be to load all our files in the `First` bucket and then within each file we `push` the function to our custom buckets arrays and then queue them e.g. like we do currently with `FirstWorldInit` and …
=> Safer changing of killer in actor on death

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_whirling_death.nut
- Gain +1 reach with every attack for one turn.
- For 1-handed flails perform a free attack against an adjacent enemy with lower current Reach than you, but with 50% less damage.
- For 2-handed flails gain +10% chance to hit the head per current Reach difference between you and the target, if you have higher Reach.
=> refactor: rework whirling death perk

mod_reforged/config/config.nut, mod_reforged/msu_systems/mod_settings.nut
Should be merged after #362 because that PR removes the application of legendary difficulty from enemies.
=> refactor: remove legendary difficulty setting

scripts/!mods_preload/mod_reforged.nut
This is not the best solution but should work for now. For a more permanent solution we should implement the `ShieldDamageMult` character property system, but I would not do that in Reforged right now - instead that should be done in a larger framework mod such as my modular vanilla mod idea.
=> fix: shield expert reducing damage to shields

mod_reforged/hooks/skills/effects/bleeding_effect.nut
Currently the description shows like 4 decimal places for certain hp values
=> refactor: round debuff multiplier in bleed effect tooltip

scripts/skills/actives/rf_hook_shield_skill.nut
Because we don't want this skill to be considered an attack for the purposes of being a valid skill in other perks.
This fixes the issue currently where in the Dismemberment perk the `_hitInfo.Injuries` is null. However, this is not a permanent long-term solution because it will still trigger `onBeforeTargetHit` and similar functions on the target because it uses `this.attackEntity` in its `onUse` function. So a null `hitInfo.Injuries` will be passed. I do not know for sure if `hitInfo.Injuries` is ever expected to be null in these functions (probably it isn't), so we should try to find a solution for this issue by rethinking how to make the code of this skill work. Have opened a separate issue for that #393
=> fix: remove IsAttack being set to true in hook shield

scripts/skills/perks/perk_rf_combo.nut
- Fixes issues with skills that remove themselves after use
- Fixes issues with the used skill potentially having a different AP cost after having been used.
=> fix: combo perk to check skill validity before its use

mod_reforged/hooks/items/shields/buckler_shield.nut, mod_reforged/hooks/items/shields/greenskins/orc_heavy_shield.nut, mod_reforged/hooks/items/shields/oriental/metal_round_shield.nut, mod_reforged/hooks/items/shields/oriental/southern_light_shield.nut
Prior to our redesign of the shield paradigm, certain shields had an identity:
- Wooden Shield, your regular shield.
- Adarga, better than wooden in ranged defense, but less durable.
- Kite, quite durable and good for ranged defense.
- Heater, less durable than Kite but better for melee defense.
- Sipar, if you want a pseudo-unbreakable shield, otherwise middle of the ground defenses.
Having made most shields "unbreakable" the identities for Adarga and Sipar have been lost. Heater and Kite still maintain their identity thanks to the defenses they provide. There is no reason to use Sipar anymore because Kite (and arguably even Heater) provides a better overall mix of defense stats considering the lower fatigue cost.  Adarga is overwhelmingly better than wooden shield. 
This PR improves the …
=> Balance adarga and sipar shields

mod_reforged/hooks/items/shields/shield.nut
A new `getDefenseFractionFromFatigue` function allies submods to much easier tweak aswell as disable the fatigue defense mechanic for shields.
The Reach Tooltip is no longer shown on a shield without any reach.
=> Refactor reforged shield mechanics to make them more moddable and changable

mod_reforged/config/item_names.nut, mod_reforged/hooks/msu.nut
This PR was a spontaneous idea of mine when I saw that vanilla only has two famed swordlance names. So I went and added a few names here and there.
It also includes a proposal for a new `::MSU.Array.removeValues` function. The singular removeValue function of MSU is not very performant if we want to remove a list of names as it would iterative several times over the same array.
=> Feat more named names

mod_reforged/hooks/items/shields/shield.nut
Subtract from 1.0 and multiply with max malus so that at 0 fatigue the multiplier is 1 and not 0.
=> fix: calculation for shield defense fatigue multiplier

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_bloodlust.nut
Instead of a flat Fatigue Recovery bonus e.g. +3 per stack, I went with a % based bonus so the entire perk is much more clean this way. 50% increased Fatigue Recovery means for a bro with 15 base recovery you get 7 additional Fatigue recovery next turn. And this is fine imo.
=> balance: bloodlust to recover fatigue instead of reducing fatigue cost

scripts/skills/actives/rf_encourage_skill.nut
- Reduce range to 2 tiles.
- Increase resolve bonus to 50%.
- Make usable once per turn.
- Prevent use on Fleeing characters.
- Allow using on characters whose morale state is lower than you per tile of distance.
=> refactor: rework encourage skill

scripts/!mods_preload/mod_reforged.nut
This is meant to enforce testing of that system. Eventually the plan is to inporporate it into reforged in which case this commit will have to be reverted.
Here is the repository: https://github.com/Battle-Modders/Poise-System
=> refactor: require Poise System temporarily

scripts/skills/actives/rf_command_skill.nut
- Anyone using command skill now creates a default log (like for example using Shieldwall)
- Enemies using command skill outside of your view no longer produces logs
=> refactor: add new log and isHiddenToPlayer logic to command skill

scripts/skills/actives/rf_adjust_dented_armor_ally_skill.nut, scripts/skills/actives/rf_adjust_dented_armor_skill.nut
These are the same sfx used for when you repair gear in towns.
It may be inrealistic how "adjusting armor", and no less quickly and on the battlefield causes smithing sfx. But I find it a completely find sfx as it's also not used by other skills in combat.
=> refactor: add sound effects for adjusting dented armor

mod_reforged/hooks/msu.nut
This fixes situations where printing (1.0 + 2 * 0.03) would print 5.99999% instead of 6%.
=> fix: floating point errors in colorizeMult and colorizeFraction

mod_reforged/hooks/skills/actives/puncture.nut, mod_reforged/hooks/skills/special/double_grip.nut
I really don't like that we have to overwrite the vanilla function and do the switcheroo but I don't know if there is a cleaner way. Please suggest a better way if possible.
=> fix: puncture being affected by reforged reworked double grip

mod_reforged/hooks/config/character_names.nut
This adds more variety for southern names:
- Add 59 new names.
- Extend the vanilla "southern last names" list by prefixing `Ibn` and `Al-` to all the first names.
=> feat: add more southern names and extend last names using basic names

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_offhand_training.nut
- Remove free swap.
- Instead of only tool, extend the one free use per turn to all offhand items less than 10 weight.
=> refactor: rework offhand training

mod_reforged/hooks/items/shields/special/craftable_kraken_shield.nut, mod_reforged/hooks/items/shields/special/craftable_lindwurm_shield.nut, mod_reforged/hooks/items/shields/special/craftable_schrat_shield.nut
- Kraken Shield: Improve ReachIgnore to 3 and reduce adjacent opponents Resolve by 10.
- Lindwurm Shield: Lightest shield that provides great defenses and durability. Improve melee defense from 17 to 20 and reduce ranged defense from 25 to 20 but reduce StaminaModifier greatly from -14 to -8. Durability slightly reduced from 250 to 200.
- Schrat Shield: Improve ReachIgnore to 3 and spawn a sapling when hit, losing durability, but regenerates durability over time.
=> feat: improve craftable shields by giving them unique identities

mod_reforged/config/perk_defs.nut
- Require at least 2 weapon perk groups to be present in the character's perk tree.
- Require at least 1 weapon perk to be unlocked.
=> refactor: add prerequisites for weapon master perk

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_sanguinary.nut
Also add StatusEffect type to it so that the uses remaining are shown in an effect tooltip.
=> refactor: restrict sanguinary to max two triggers per turn

mod_reforged/hooks/items/weapons/crossbow.nut, mod_reforged/hooks/items/weapons/greenskins/goblin_crossbow.nut, mod_reforged/hooks/items/weapons/heavy_crossbow.nut, mod_reforged/hooks/items/weapons/light_crossbow.nut, mod_reforged/hooks/items/weapons/named/named_crossbow.nut, mod_reforged/hooks/items/weapons/named/named_handgonne.nut, mod_reforged/hooks/items/weapons/oriental/handgonne.nut, mod_reforged/hooks/skills/actives/fire_handgonne_skill.nut, mod_reforged/hooks/skills/actives/reload_bolt.nut, mod_reforged/hooks/skills/actives/shoot_bolt.nut, mod_reforged/hooks/skills/actives/shoot_stake.nut
The goal of showing them in nested tooltips is achieved instead by ensuring that the reload skill is always added to the dummy player. This keeps the skills themselves functioning as vanilla so that mods which use these skills do not run into unintended behavior.
Fixes [this issue](https://discord.com/channels/1006908336991645757/1268104130803535964).
=> fix: revert reload skills to vanilla behavior of removal upon firing

mod_reforged/hooks/skills/actives/hook.nut, mod_reforged/hooks/skills/actives/impale.nut, mod_reforged/hooks/skills/actives/reap_skill.nut, mod_reforged/hooks/skills/actives/repel.nut, mod_reforged/hooks/skills/actives/rupture.nut, mod_reforged/hooks/skills/actives/strike_skill.nut, mod_reforged/hooks/skills/perks/perk_mastery_polearm.nut
And apply the AP reduction from our polearm mastery hook. This avoids applying the bonus twice because modular vanilla reduces it based on Base ActionPointCost within the onAfterUpdate of the active skills and polearm mastery perk skill order is before that of actives.
=> fix: overwrite modular vanilla reduction of AP cost for polearm skills

mod_reforged/config/msu_excluded_injuries.nut
- Add exclusion for Broken Ribs and Fractured Ribs to all undead and move exclusion of Pierced Side from skeleton only to all undead because these injuries affect Fatigue only.
- Exclude Burnt Face, Burnt Leg and Burnt Hands from skeletons.
- Exclude Cut Arm Sinew from skeletons.
- Reorganize the injuries for readability by separating them into types.
- Remove duplicate entries.
=> refactor: adjust excluded undead injuries

mod_reforged/hooks/skills/perks/perk_mastery_axe.nut, scripts/items/weapons/rf_poleaxe.nut
- Set Hook Shield to have the max range of the weapon it gets added to, instead of always having a range of 1.
- Rearrange Poleaxe skills to move the AOO to the front and Impale to the end. So it is now Hew, Strike, Impale.
=> Fix axe skills

mod_reforged/hooks/skills/backgrounds/hedge_knight_background.nut, mod_reforged/hooks/skills/backgrounds/swordmaster_background.nut
- Remove manual removal of mastery perks from swordmaster bg because we restricted him to 1 weapon perk group so it's redundant now.
- Add tooltip about free sword mastery perk for swordmaster bg.
- Add lone wolf at tier 1 of hedge knight background perk tree.
=> Swordmaster and Hedgeknight background adjustments

mod_reforged/actor_tooltip_functions.nut, mod_reforged/config/items.nut, mod_reforged/hooks/items/item.nut, scripts/!mods_preload/mod_reforged.nut
As it turns out the crash is primarily fixed by fixing a bug over at Modern Hooks that caused `FirstWorldInit` bucket to run too early causing the dummy player to be initialized in a weird limbo state. I've also improved some stuff over at nested tooltips framework and this PR changes existing code to align with those improvements.
In view of the above, this PR is no longer a "crash fix" PR but rather an improvement PR to update our setup based on nested tooltips framework update and fix a technical issue on our side with regards to how we fetch the skills: The main technical change in Reforged is that our `getSkills` function now uses switcheroos and calls `onEquip` instead of creating a copy of the item and equipping that on the dummy player. This is important because certain items have …
=> fix: random crash during getting item skills

mod_reforged/hooks/entity/world/location.nut
Because this is an option available in the default vanilla options for the game.
=> refactor: remove auto pause on leaving location

mod_reforged/hooks/entity/tactical/enemies/necromancer.nut
Because with Take Aim now being given with crossbow mastery, it makes sniping them too easy without this change.
=> balance: add soul link to necromancer

mod_reforged/hooks/skills/backgrounds/character_background.nut
This should cover all backgrounds added by mods which do not have their own custom perk tree logic defined.
=> feat: generate a basic dynamic perk tree for all backgrounds by default

mod_reforged/hooks/skills/racial/alp_racial.nut, mod_reforged/hooks/skills/racial/ghost_racial.nut, mod_reforged/hooks/skills/racial/golem_racial.nut, mod_reforged/hooks/skills/racial/lindwurm_racial.nut, mod_reforged/hooks/skills/racial/schrat_racial.nut, mod_reforged/hooks/skills/racial/serpent_racial.nut, mod_reforged/hooks/skills/racial/skeleton_racial.nut, mod_reforged/hooks/skills/racial/spider_racial.nut, mod_reforged/hooks/skills/racial/vampire_racial.nut, scripts/skills/racial/rf_zombie_racial.nut
This PR does
- Add hyperlinks for existing tooltip lines of racial effects
- Add new hyperlinked tooltip line for morale immunity to racial effects
I confirmed the new hyperlinks in the following screenshots working correctly.
I haven't checked the other entities, where I only added hyperlinks.
=> Improve racial tooltips

mod_reforged/hooks/entity/tactical/enemies/bandit_raider.nut, scripts/entity/tactical/enemies/rf_bandit_bandit.nut, scripts/entity/tactical/enemies/rf_bandit_highwayman.nut, scripts/entity/tactical/enemies/rf_bandit_killer.nut, scripts/entity/tactical/enemies/rf_bandit_robber.nut, scripts/entity/tactical/enemies/rf_bandit_vandal.nut
equip throwing weapons to bag
give vandal, raider and highwayman quick hands
remove longsword from killer
Code on fast bandits can probably be further improved by adding to a single list for weapon rolls depending on getting throwing net or not, but I don't recall the code for this and don't know where a reference is.
=> refactor: improve code and design of bandits

mod_reforged/hooks/entity/world/locations/legendary/black_monolith_location.nut
Similar to how vanilla recovers up to 6 troops before combat up to a maximum of 47.
We have an assortment of regular skeletons and if decanus, centurion, legatus and vampire lord are below their desired numbers we also add them to the pool of potential entities.
=> refactor: recover some troops in black monolith before combat

mod_reforged/hooks/config/strings.nut
All of these effects are positive, but were using the negative color.
I did not do a complete sweep here, nor did I fix any instances of values which are green, but should be red.
This is just a first rough correction with more to go over time as we discover more cases.
=> refactor: invert coloring of several values in perk description

mod_reforged/hooks/skills/traits/brute_trait.nut, mod_reforged/hooks/skills/traits/disloyal_trait.nut, mod_reforged/hooks/skills/traits/gluttonous_trait.nut, mod_reforged/hooks/skills/traits/greedy_trait.nut, mod_reforged/hooks/skills/traits/loyal_trait.nut, mod_reforged/hooks/skills/traits/spartan_trait.nut
This PR adds three new tooltips for vanilla effects that were not explained before.
It also improves previous adjustments to tooltips according to our recently fleshed out coding standards
- usage of more/less
- start id for effect tooltip lines at 10
=> Refactor improve trait tooltips

scripts/skills/perks/perk_rf_kingfisher.nut, scripts/skills/perks/perk_rf_trip_artist.nut
For Trip Artist and Kingfisher. Because these perks are meant to work with a net equipped in the offhand.
=> fix: ensure that the throw net skill comes from an offhand item

scripts/skills/perks/perk_rf_ghostlike.nut
E.g. Lunge. Because you remove the enemy in onAnySkillExecuted but he gets added back in onMovementFinished.
=> fix: ghostlike not removing the enemy with delayed attacks

mod_reforged/msu_systems/mod_settings.nut, mod_reforged/msu_systems/tooltips.nut
The default Hotkey is CTRL + Spacebar
Reminder that normal Wait hotkey is Spacebar
End Turn for all Characters (vanilla) has the hotkey **R**. I prefer a single button hotkey but there are not so many options left. And honestly you probably use **Wait Round** a bit less than **End Round**.
=> feat: add keybind support for wait round action

mod_reforged/config/reach.nut, mod_reforged/hooks/items/weapons/weapon.nut
This should cover all melee weapons added by mods (unless they use a WeaponType we are not aware of) and assign them an appropriate Reach value.
In my testing this produced very similar results for Reach for all weapons as to what we have manually set currently in Reforged.
=> feat: add automatic assignment of default reach for weapons

scripts/mods/mod_reforged/perk_group_collections/pgc_rf_exclusive_1.nut, scripts/mods/mod_reforged/perk_group_collections/pgc_rf_shared_1.nut, scripts/mods/mod_reforged/perk_groups/pg_rf_ranged.nut
This is a small change to the names of the ranged and shield perk groups.
I suggest Ranged Weapons be renamed to Ranged Fighting and Shield be renamed to Shield Fighting
I think this style of group name fits better with the other two groups in this category, Swift Strikes and Powerful Strikes.
=> refactor: rename ranged perk group and exclusive and shared collections

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_opportunist.nut
- Instead of halving the AP cost of the first 2 throwing attacks in the battle, it now halves the cost of all throwing attacks but only during the first round of battle.
- Instead of recovering 4 AP after stepping on a corpse, it now makes the next throwing attack cost no AP. (Still reduces its Fatigue cost by 50% like before).
The first point is somewhat of a sidegrade as you can now potentially unleash 4 throwing attacks during the first turn if you want if you don't move from your position. But it makes more sense thematically to me as an "opportunistic" playstyle and doesn't suffer from the weird situation we have currently where you are fatigued out after 4 rounds and still have the halved AP cost for the throwing attacks.
The second point reduces the silly chain of corpse hopping …
=> refactor: rework opportunist to reduce ap cost instead of ap recovery

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_tempo.nut
- The first 2 hits during a turn recover 2 AP each but cause the Initiative bonus to expire.
- Missed attacks no longer consume the attacks for AP recovery.
=> refactor: rework tempo to lose initiative upon ap recovery

mod_reforged/hooks/skills/skill_container.nut
This fixes glitchy behavior when swapping equipped bandages This also fixes a rare crash during battle, when opening the inventory
=> fix(vanilla): missing isNull check during querySortedByItems

mod_reforged/hooks/skills/backgrounds/nomad_background.nut, mod_reforged/hooks/skills/backgrounds/nomad_ranged_background.nut
I decided to just remove all code related to throw dirt on nomad background instead of commenting out those sections. It's easy enough to look up the history of the file if we ever decide to revert it. If my logic is flawed please let me know.
=> balance: remove throw dirt from nomad background and allow knave group

scripts/mods/mod_reforged/dynamic_spawns/units/barbarian_units.nut
Currently Armored Unholds spawn early and normal Unholds spawn late.
That is likely because all 4 options cost the same amount of resources. When they get sorted, their order is undefined.
This is a bandaid fix that solves the issue by giving them all slightly different costs to preserve the correct order.
This fix might just bury the underlying problem.
I don't know how the subparty system was supposed to work and currently works. Maybe it was supposed to raise the cost of the individual unit options by the cost of their subparties during sorting, which would have solved this issue.
=> fix: barbarian unholds spawning in the wrong order

mod_reforged/hooks/items/shields/special/craftable_schrat_shield.nut
Currently there is this bug when you move to another tile while in ZOC and while you have the craftable Schrat shield equipped.
An enemy tries to hit you, misses and damages your shield. Then a Sapling will spawn and randomly chooses the tile you are currently moving into.
Your movement finishes and now you and your sapling occupy the same tile, causing undefined behavior in combat.
I tested this fix out ingame and the scecnario I describe no longer happens, while you still spawn saplings during enemies turns
=> refactor: prevent schrat shield from triggering during users turn

mod_reforged/hooks/misc.nut, mod_reforged/hooks/mods/mod_dpf/classes/perk_tree.nut, mod_reforged/hooks/scenarios/world/starting_scenario.nut
The first commit is just refactoring, by encapsulating the weapon group identification logic, into a helper function.
The second commit will guarantee that all starting brothers from origins have at least one weapon group that works with their equipped weapon.
This approach makes sure that most custom perk tree changes by that origin are preserved.
=> Refactor starting brother weapon group

mod_reforged/hooks/entity/tactical/actor.nut
This fixes two issues:
- **Long Reach** ignores the minimum requirement for surrounding. 1 Guy with long reach guarantees that the target is surrounded by 1 guy at all times
- The property `StartSurroundCountAt` is applied twice. This does not matter currently because no effects in Vanilla/Reforged make it so your surround-count starts at a later point
=> fix: long reach ignoring minimum surround count

mod_reforged/hooks/skills/actives/charm_skill.nut, mod_reforged/hooks/skills/actives/fire_mortar_skill.nut, mod_reforged/hooks/skills/actives/goblin_whip.nut, mod_reforged/hooks/skills/actives/grant_night_vision_skill.nut, mod_reforged/hooks/skills/actives/hex_skill.nut, mod_reforged/hooks/skills/actives/horrific_scream.nut, mod_reforged/hooks/skills/actives/insects_skill.nut, mod_reforged/hooks/skills/actives/miasma_skill.nut, mod_reforged/hooks/skills/actives/nightmare_skill.nut, mod_reforged/hooks/skills/actives/possess_undead_skill.nut, mod_reforged/hooks/skills/actives/raise_undead.nut, mod_reforged/hooks/skills/actives/root_skill.nut, mod_reforged/hooks/skills/actives/sleep_skill.nut, mod_reforged/hooks/skills/actives/throw_golem_skill.nut, mod_reforged/hooks/skills/actives/unstoppable_charge_skill.nut
I only verified the tooltip working correctly for a Geist, but the code is copy-pasted to all other places so I assume all of them work correctly.
=> refactor: add range tooltip line for many enemy-only skills

mod_reforged/hooks/config/strings.nut, scripts/skills/effects/rf_rattled_effect.nut, scripts/skills/perks/perk_rf_rattle.nut
removing stun and daze as exceptions is necessary because the perk is just too stinky otherwise.
The reach modifier increase to 3 is a bit more experimental. I think we should probably instead have rattled reduce matk/mdef by 10 and ratk/rdef by 20 instead as it's useful in more situations and better than reach, but since we're on a time crunch this is okay for now unless you agree and wanted to do it quick.
=> Uber rattle buff

scripts/skills/perks/perk_rf_decisive.nut
- Decisive now always displays the effect icon, even with 0 Stacks
- Decisive now only shows its mini icon while you have at least 1 stack
These changes should make it easier for the player to quickly see, whether they are allowed to use Wait or must end the turn immediately during turn 1 of a combat.
=> Refactor decisive display

mod_reforged/config/z_nested_tooltips.nut, mod_reforged/hooks/ui/screens/tooltip/tooltip_events.nut, ui/mods/mod_reforged/js_hooks/screens/character/modules/character_screen_left_panel/character_screen_stats_module.js
Just like for the other attributes in the characterscreen before, this PR aims to add information about base Reach, weapon Reach, Reach Modifier and Offensive/Defensive Reachignore to the tooltip for Reach.
- For that, we need to send the entityID as an argument into the bindTooltip.
- I also had to remove an old, seemingly redundant bindTooltip for Reach, that would have otherwise overwritten my adjust bindTooltip with the entityID.
- Finally I hooked the MSU function `onQueryMSUTooltipData` because tooltips like that for Reach pass through that event, where I can then add my additional info to them
I have not tested whether the Reach Modifier field works, but the other four seem to work fine.
=> Feat reach base modifier values

mod_reforged/hooks/crafting/blueprint.nut, mod_reforged/hooks/crafting/crafting_manager.nut, mod_reforged/msu_systems/mod_settings.nut
**Always** treats all Blueprints in the game as if you've already crafted them once before
**One Ingredient Available** treats all Blueprints in the game, for which you have at least one Ingredient, as if you've already crafted them once before
**All Ingredient Available** treats all Blueprints in the game, as if you've never crafted them once before
**Vanilla** applies the Vanilla filtering behavior
This hook preserves any overwritten Qualified-behavior like that of Snake Oil. 
Those recipes will not show up, no matter what setting is active, if those overwritten rules forbid it.
=> feat: add mod setting to control visibility of blueprints in taxidermist

mod_reforged/hooks/ui/screens/tactical/modules/turn_sequence_bar/turn_sequence_bar.nut, ui/mods/mod_reforged/generic.css, ui/mods/mod_reforged/js_hooks/screens/tactical/modules/tactical_screen_turnsequencebar/turnsequencebar_module.js
When Taro did the same for the character screen he opted to send new Reach entries via the data structure to js.
For this change I decided to instead replace the existing morale values as I found that easier to implement and unlikely to cause issues.
This is how it looks now with this PR:
Here is how it lookes after doing Bagels issue
Here Reach looks in the character screen (before this PR):
=> refactor: replace morale progressbar on turn sequence bar with reach

mod_reforged/hooks/entity/tactical/player.nut, mod_reforged/hooks/skills/backgrounds/character_background.nut, mod_reforged/msu_systems/mod_settings.nut
This PR does two things
- Add a Mod Setting for the already existing "Attribute Projection" tooltip in character backgrounds. With this the player can turn it on and off
- Add a new Base Attribute Range tooltip for backgrounds showing the minimum and maximum range of each Attribute. After hiring this will also show the current base attribute. In the Mod Settings the display can be changed.
=> feat: attribute projection setting and attribute base range display

scripts/ai/tactical/behaviors/ai_rf_kata_step.nut
Causes a crash if `::Const.AI.VerboseMode` is set to true.
=> Fix faulty logInfo call ai_rf_kata_step

scripts/skills/perks/perk_rf_strength_in_numbers.nut
Move isPlacedOnMap checks into the getter functions, when the getTile() checks are actually required
Via hyperlinks you can view this tooltip for actors not placed on a map. This will then cause an error, which is catched by a try block and causes the following logs:
=> fix: error when fetching tooltip for strenght in numbers

mod_reforged/hooks/scenarios/world/starting_scenario.nut
Except for bros whose perk tree is based on a fixed template. This system ensures that all the factors such as talent stars, equipment etc. assigned during starting scenario start is taken into consideration for the perk trees of the starting bros.
=> fix: regenerate perk tree for bros when starting an origin

mod_reforged/hooks/config/tip_of_the_day.nut
For me tips of the day should primarily explain/spotlight niche or new mechanics
Spoilers for strengths/weaknesses of enemies are fine.
And I can look past flavourful world building additions.
What it shouldn't do is:
- throwaway fortune cookie lines
With this PR I suggest to add:
- Advertisments for other origins
To the list of things that `tip of the day` should not be used for. 
I consider that bloat. The origins can be seen and looked through at any point in time in the main menu.
=> refactor: remove tips of the day which advertise origins

scripts/skills/perks/perk_rf_decisive.nut
With the last release, we made it so decisive shows, no matter how many stacks you have, meant to help the player during combat to remember this perks restriction.
As a result it also shows outside of battle.
This PR adjusts the perk to always show during combat but never outside of it
=> refactor: hide decisive outside of combat

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_promised_potential.nut, scripts/skills/perks/perk_rf_realized_potential.nut
- Promised Potential now has a 100% chance to succeed at level 11 if the user has the **Player Character** perk
- Promised Potential perk description has been simplified a lot by moving all the effects into the **Realized Potential Description**
I verified that this change works by setting the WillSucceed chance to 0 and printing the WillSucceed chance right before it is swapped from the PlayerCharacter trait.
Then I loaded a Random Solo with a pauper starter and confirmed that he succeeded at level 11
**Player Character** is technically a trait but I decided to just call it like this
=> refactor: move all actual effects from PP to realized potential

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_the_rush_of_battle.nut
Stacks gained during each turn are tracked separately and expire at the end of their next turn.
=> refactor: improve rush of battle stacks management

mod_reforged/hooks/config/tip_of_the_day.nut, scripts/!mods_preload/mod_reforged.nut
The purpose of this feature was to make loot drop only if the player and player animals did at least 50% damage to the dying entity, regardless of who the killer is. However, this was accomplished by changing the `_killer` which leads to conflicts with other mods which expect the `_killer` to be the real killer. So, in view of greater compatibility with mods, this feature should be removed until a more stable and more compatible method of accomplishing this can be achieved.
Associated bug report on Discord: https://discord.com/channels/1006908336991645757/1327651957657305099
=> refactor: remove changing killer during onDeath

mod_reforged/hooks/states/world_state.nut
Vanilla calls `setAutoPause(true)` at the start of `startNewCampaign` but never sets it to `false` again.
That does not cause problems in vanilla because every dialog or other window that might pop-up will always call a `this.setAutoPause(false);`, when they are closed and vanilla always spawns an intro event for every origin at the start of a new campaign.
=> fix(vanilla): scenarios without intro event locking up the game

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/entity/tactical/enemies/goblin_fighter.nut, mod_reforged/hooks/entity/tactical/humans/desert_devil.nut, scripts/skills/actives/rf_kata_step_skill.nut, scripts/skills/perks/perk_rf_fencer.nut, scripts/skills/perks/perk_rf_kata.nut, scripts/skills/perks/perk_rf_swordmaster_blade_dancer.nut, scripts/skills/perks/perk_rf_tempo.nut
- Kata Step
- Now costs +2 fatigue based on movement cost of starting tile (up from +0).
- Now requires Cutting damage type.
- Code is improved to have the requirements be more granular as member variables. Entities code where it was using IsForceEnabled is updated to use these new member variables.
- The effect of Blade Dancer perk on Kata Step has been fully encapsulated within that perk's file.
- Fencer perk now removes the Damage Type requirement from Kata Step while a fencing sword is equipped.
- Rework tempo
- Gain a stack for every hit/miss.
- Each stack grants +15 Initiative. This lasts until your first attack next turn or waiting/ending next turn.
- During your next turn gain half of the stacks of the previous turn as additional Action Points and attacks build 5% less fatigue per …
=> Rework sword perks

mod_reforged/hooks/skills/actives/shieldwall.nut, mod_reforged/hooks/skills/effects/shieldwall_effect.nut, scripts/skills/actives/rf_hook_shield_skill.nut
- Allow using on targets using Shieldwall. Removes Shieldwall in this case.
- Second use on the same target refunds its AP cost.
- Increase Fatigue Cost from 15 to 25.
=> refactor: improve hook shield

mod_reforged/hooks/config/strings.nut, scripts/skills/actives/rf_dynamic_duo_shuffle_skill.nut, scripts/skills/perks/perk_rf_dynamic_duo_abstract.nut
- Shuffle now moves the target to the front in the turn order.
- AOE melee skills have 0 melee skill when attacking partner (which means they will have the minimum Hit Chance i.e. 5%) and will inflict 50% less damage.
=> refactor: improve dynamic duo shuffle and give aoe benefit

scripts/ai/tactical/behaviors/ai_rf_command.nut
There are three `onVerifyTarget` in the old implementation. I couldnt replace the third one though as it simulates future tiles and isUsableOn always takes the skill owners current tile as the origin.
I tested this with a toggle of the before and after condition like this:
Then I pumpted the score for ai_command x100 and set its minimum range to 2 and maximum range to 1 = (impossible to use)
I did 3 (each) back&forth tests with both setups in a fight against 4 heralds
The marked herald in exactly this setup consistently froze the game with the old check.
After the check swap (see first screenshot), I got no more freezes here. Instead that guy tried to move elsewhere
This is not a complete test by all means but good enough for me
=> Fix command ai freeze

mod_reforged/hooks/ai/tactical/behaviors/ai_attack_throw_net.nut
The function was returning integer sporadically, which caused "trying resume a 'integer'" crash.
Also, we won't get score until we cycle through the original generator.
=> fix: throw net behavior with kingfisher

mod_reforged/hooks/items/shields/named/named_shield.nut
Because rolling Durability in the Reforged shields design is practically useless.
=> feat: remove Condition roll from named shields

mod_reforged/hooks/skills/actives/recover_skill.nut
Features:
- Recover cannot be used after a movement or having used any skill.
- Your turn ends immediately after using Recover.
=> refactor: restrict recover to be unusable after movement or skill use

mod_reforged/hooks/config/tip_of_the_day.nut, mod_reforged/hooks/items/weapons/weapon.nut, mod_reforged/hooks/retinue/followers/blacksmith_follower.nut
In Vanilla: normal player weapons are never dropped if they have 11 or less condition unless you have the blacksmith retinue.
This PR will make it so weapons that were dropped from a player character always drop, even if they have 0 condition.
I have not yet tested this out ingame
We also need to verify what happens if you try to loot those 0 condition items again and equip them. Although this shouldnt be too buggy as that would also be possible with the blacksmith retinue in vanilla
=> feat: always preserve dropped player weapons

mod_reforged/hooks/config/faction_southern.nut, mod_reforged/hooks/entity/tactical/humans/conscript.nut, mod_reforged/hooks/entity/tactical/humans/conscript_polearm.nut, mod_reforged/hooks/entity/tactical/humans/engineer.nut
- increase gunner rdef from 20 to 25
- give frontline conscript dodge
- give backline conscript long reach with polearm and leverage with mace
- give engineer dodge
=> balance: buff southern faction

scripts/skills/perks/perk_rf_line_breaker.nut
Not noteworthy for patchnotes. 
This function is never called currently because of a vanilla bug, where knock_back does not call onTargetHit or onTargetMissed
=> fix: crash when trying to apply staggered via line breaker perk

scripts/skills/perks/perk_rf_flail_spinner.nut
Hopefully this reduces/elminiates the cases where AI evaluation gets stuck due to killing someone with a delayed attack. Once a proper solution to that issue is found and implemented, this can be reverted.
=> refactor: make flail spinner non-lethal for NPC users

scripts/skills/actives/rf_hook_shield_skill.nut
- Ignore bonus to defense from Shieldwall
- Cannot be used against a shieldwalled target if his adjacent ally is also using shieldwall.
=> refactor: improve hook shield usage against shieldwall target

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/actives/cascade_skill.nut, mod_reforged/hooks/skills/actives/flail_skill.nut, mod_reforged/hooks/skills/actives/hail_skill.nut, mod_reforged/hooks/skills/actives/lash_skill.nut, scripts/skills/actives/rf_flail_pole_skill.nut, scripts/skills/actives/rf_lash_pole_skill.nut
- Improve vanilla flail skills tooltips.
- Mention Shieldwall in addition to the defense bonus of Shields for clarity.
- Adjust Cascade and Hail tooltips for the Reforged system of three attack rolls but one strike.
- Add missing range entry to pole flail and lash skills.
- Fix pole flail and lash skills not showing too close in hit factors.
=> Flail tooltips improvements

scripts/mods/mod_reforged/perk_groups/special/pg_special_rf_fencer.nut
Complete setup is:
- No chance if no sword perk group.
- No chance if Projected Average Initiative is below 150 or Projected Average Melee Skill is below 85.
- For each point of projected average Initiative above 150 and Melee Skill above 85 the multiplier is increased by 0.05.
- So a projected Initiative of 160 will have  1.5 multiplier. 170 will have 2 multiplier.
- Similarly 90 projected melee skill will have 1.25 multiplier.
- Someone with projected Initiative of 160 and Melee Skill of 90 will have 1.75 multiplier.
The multiplier is then multiplied by the base chance which is 25%.
=> refactor: use projected attributes instead of talents for fencer special

scripts/skills/perks/perk_rf_flail_spinner.nut, scripts/skills/perks/perk_rf_whirling_death.nut
In a recent bug report the user crashed when a Fallen Hero spun the flail.
According to the log it looks like the Fallen Hero died to Riposte/Rebuke while spinning the flail.
If a dying actor instantly uncoupled from its skill container and/or deconstructs its actor object then that would explain, why we crash during the `onVerifyTarget` function.
That function assumes this skill to be attached to a skill container and that container to be attached to an actor.
My solution is to check for the coupling of the container before spinning the flail
=> fix: add safety check for skill containers before spinning the flail

mod_reforged/hooks/entity/tactical/humans/knight.nut, mod_reforged/hooks/entity/tactical/humans/noble_arbalester.nut, mod_reforged/hooks/entity/tactical/humans/noble_billman.nut, mod_reforged/hooks/entity/tactical/humans/noble_footman.nut, mod_reforged/hooks/entity/tactical/humans/noble_greatsword.nut, mod_reforged/hooks/entity/tactical/humans/noble_sergeant.nut, mod_reforged/hooks/entity/tactical/humans/standard_bearer.nut, scripts/entity/tactical/humans/rf_arbalester_heavy.nut, scripts/entity/tactical/humans/rf_billman_heavy.nut, scripts/entity/tactical/humans/rf_fencer.nut, scripts/entity/tactical/humans/rf_footman_heavy.nut, scripts/entity/tactical/humans/rf_herald.nut, scripts/entity/tactical/humans/rf_heralds_bodyguard.nut, scripts/entity/tactical/humans/rf_knight_anointed.nut, scripts/entity/tactical/humans/rf_man_at_arms.nut, scripts/entity/tactical/humans/rf_marshal.nut, scripts/entity/tactical/humans/rf_squire.nut
This PR does two things:
- guarantees surcoats on all noble troops (instead of there being a 10%-50% chance for them to spawn without one
- this increases visual clarity during bigger fights with multiple noble houses or when they have mercenaries in their partiy
- make surcoat spawnchance a member variable
- some noble troops during special events might not (or with reduced chance) spawn with surcoats (e.g. deserted, hexed or otherwise betraying nobles)
=> refactor: guarantee a surcoat to spawn on all noble troops

mod_reforged/hooks/items/weapons/heavy_crossbow.nut
Because the skill is removed and re-added upon every shoot bolt.
=> fix: heavy crossbow reload ap cost change not being persistent

mod_reforged/hooks/skills/skill.nut
Vanilla doesnt differentiate different types of bad terrain. It doesnt know whether this specific bad terrain actually influences your hitchance.
Also with our expanded tooltips, it is much easier to see the effects that the bad terrain has on you.
Currently the only bad terrain there is is swamp, which applies its effects continuously, being visible in the attributes.
*edit1:* Swamp also doesn't affect ranged skill, and yet it shows up as a "negative hitfactor", when you aim with a ranged skill onto an enemy while you stand in swamp
So I deem these entries as bloat/misleading
=> refactor: remove vanilla mention of bad terrain in hitfactors

mod_reforged/hooks/config/item_names.nut
I noticed that "Reach" is used in 4 different named weapons as a name, so I reduced it to only be used for Bows.
I also removed "Bardiche" and "Voulge" as possible names
=> Refactor remove named names

mod_reforged/hooks/skills/backgrounds/gladiator_background.nut
There are two ways to go about this:
- We make the gladiators from the gladiator origin also follow this random trait assignment from the background script. I would prefer this, but I can't find a clean way to do this short of overwriting the entire `onSpawnAssets` function of  `gladiators_scenario`.
- Or we let the origin gladiators get their manual traits from `onSpawnAssets` and remove them from this random assignment. I have gone with this solution in this PR.
Unless someone can suggest a cleaner/better solution?
=> fix: gladiators from the gladiator origin getting double arena traits

mod_reforged/hooks/items/weapons/golems/golem_cleaver_hammer.nut, mod_reforged/hooks/items/weapons/golems/golem_mace_flail.nut, mod_reforged/hooks/items/weapons/golems/golem_mace_hammer.nut, mod_reforged/hooks/items/weapons/golems/golem_spear_sword.nut, mod_reforged/hooks/skills/actives/golem_bash_skill.nut, mod_reforged/hooks/skills/actives/golem_batter_skill.nut, mod_reforged/hooks/skills/actives/golem_cleave_skill.nut, mod_reforged/hooks/skills/actives/golem_decapitate_skill.nut, mod_reforged/hooks/skills/actives/golem_knock_out_skill.nut, mod_reforged/hooks/skills/actives/golem_lash_skill.nut, mod_reforged/hooks/skills/actives/golem_slash_skill.nut, mod_reforged/hooks/skills/actives/golem_thrust_skill.nut, mod_reforged/hooks_helper.nut
- Dual weapons hold an instance of each weapon.
- Dual weapons now get assigned appropriate stats and weapon types based on the two weapons they are based off of.
- Golem skills use one of the instances of the weapons inside the dual weapon for its damage values.
=> feat: add custom framework for golem dual weapons and skills

mod_reforged/hooks/config/character.nut, mod_reforged/hooks/entity/tactical/actor.nut
To reduce morale cascades for large enemy groups.
=> feat: increase resolve +1 per ally during fleeing allies morale check

mod_reforged/hooks/config/tip_of_the_day.nut
These tips give information that is either too vague or information that should be already well within the knowledge of someone playing Reforged. Removing these tips allows more important tips to appear more frequently.
=> feat: remove some vanilla tips of the day

scripts/skills/actives/rf_encourage_skill.nut, scripts/skills/perks/perk_rf_supporter.nut
- Supporter is buffed and now allows trying to free an ally from net 3 times instead of 2 per turn when standing next to him. Can now use a 4 AP skill targeting an ally and still have 8 AP left over to do two 4 AP actions.
- Encourage at 4 AP now disallows moving 3 tiles and using Encourage.
=> balance: recover 3 AP from supporter and increase encourage AP cost to 4

scripts/skills/perks/perk_rf_flail_spinner.nut, scripts/skills/perks/perk_rf_whirling_death.nut
The previous implementation was only making it non-lethal for the primary target on whom the skill will be executed. Because AOE skills are used on a tile but can attack more targets, this means they could still kill those secondary targets.
See this bug report on Discord: https://discord.com/channels/1006908336991645757/1359195370474701043
=> fix: make whirling death and flail spinner non-lethal for aoe attacks

mod_reforged/hooks/items/weapons/goedendag.nut, mod_reforged/hooks/items/weapons/named/named_spetum.nut, mod_reforged/hooks/items/weapons/spetum.nut, mod_reforged/hooks/items/weapons/two_handed_mace.nut, mod_reforged/hooks/items/weapons/two_handed_wooden_flail.nut, mod_reforged/hooks/items/weapons/two_handed_wooden_hammer.nut, mod_reforged/hooks/items/weapons/warfork.nut, mod_reforged/hooks/items/weapons/woodcutters_axe.nut, scripts/items/weapons/rf_greatsword.nut
- Generally 2-tile weapons are changed to 6 AP except a few.
- Spetum and Warfork are increased in Value.
- Two-Handed 1-tile weapons are generally made to be 5 AP on their main attack and 6 AP on the secondary attacks, except the Two Handed Mace and Two Handed Wooden Hammer which are made to be 6 AP completely.
=> balance: increase AP cost of skills on two-handed weapons

scripts/skills/special/rf_polearm_adjacency.nut
This accomplishes two things:
- From a realism perspective it makes sense that others with longer weapons like to remain at a longer distance from you, so they aren't really "crowding" you the same way someone with a shorter weapon would by closing the gap with you.
- From a gameplay perspective it encourages the use of longer weapons, even in melee, against beasts and enemies who out-reach you. This helps the player have a tool to overcome the Reach Disadvantage, by using longer weapons, and also sounds great thematically when fighting bigger beasts.
=> balance: only get crowded by enemies with lower reach than you

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/perks/perk_mastery_spear.nut
Keeps the identity of the free attack on spears while making it a little more gated to use for balance. Primarily it prevents 2-tile spears e.g. Warfork, Spetum, Swordstaff from walking 2 tiles and still attacking twice.
Also remove Spearwall AP cost reduction.
=> balance: spear mastery free attack and spearwall AP reduction

mod_reforged/hooks/items/shields/oriental/metal_round_shield.nut, mod_reforged/hooks/items/shields/oriental/southern_light_shield.nut
- Sipar is a Persian word that means shield.
- Adarga is of Berber origin and also seems to be used as a name for this kind of shield so doesn't need the "shield" suffix.
There was some discussion with players about this on Discord too: https://discord.com/channels/1006908336991645757/1006908337981509725/1360465548508532919
=> feat: remove Shield from the name of Sipar and Adarga shields

mod_reforged/config/reach.nut, mod_reforged/hooks/config/faction_beasts.nut, mod_reforged/hooks/entity/tactical/enemies/lindwurm.nut, mod_reforged/hooks/entity/tactical/enemies/sand_golem_high.nut, mod_reforged/hooks/entity/tactical/enemies/sand_golem_medium.nut, mod_reforged/hooks/entity/tactical/enemies/trickster_god.nut, mod_reforged/hooks/entity/tactical/enemies/unhold.nut, mod_reforged/hooks/entity/tactical/enemies/unhold_bog.nut, mod_reforged/hooks/entity/tactical/enemies/unhold_frost.nut
BeastEnormous = 11
BeastGargantuan = 13
Lindwurm
- Huge +2 to Gargantuan
- Matk from 75 to 65
- Mdef from 10 to 0
- Gain Formidable Approach, lose Survival Instinct
Unhold/Bog Unhold
- Large to Huge
- Mdef from 10 to 5
Unhold Frost
- Large +1 to Huge +1
- Matk from 75 to 70
- Mdef from 10 to 5
Ifrit High
- Large +1 to Huge +1
Ifrit Medium
- Medium +1 to Large
=> balance: add 2 beast reach tiers, adjust reach and stats of beasts

mod_reforged/hooks/skills/actives/throw_net.nut
Examples of Huge and above beasts:
- Unhold
- Greater Flesh Golem
- Lindwurm
- Ijirok
- Ifrit High
Unholds and Ifrits are being increased in their size in another PR: #740
=> balance: make huge and above beasts immune to being netted

mod_reforged/hooks/entity/tactical/player.nut, mod_reforged/hooks/skills/backgrounds/character_background.nut
This feature has been present in MSU for a long time so we can simply use it instead of adding a new flag.
=> refactor: use msu LevelUpsSpent spent variable instead of new flag

mod_reforged/hooks/config/character.nut, mod_reforged/hooks/config/tip_of_the_day.nut, mod_reforged/hooks/entity/tactical/actor.nut, mod_reforged/hooks/ui/screens/tactical/modules/turn_sequence_bar/turn_sequence_bar.nut, mod_reforged/msu_systems/mod_settings.nut
We absolutely should have this as a mod setting and it was also requested by a member of the community not long ago. I have also added custom words for the Action Points state.
This setting allows the player to customize whether the Head Armor, Body Armor, Hitpoints, Fatigue and Action Points of a character in the tooltip are shown as numbers or as words (just line in vanilla). The setting allows to customize whether it is shown as numbers for All characters, Player Only, AI Only, or None.
=> feat: add mod setting to display actor basic values as numbers or words

mod_reforged/hooks/entity/tactical/actor.nut
In order to set a function inside the object to switcheroo it we have to get the table inside the WeakTableRef instance.
See bug log here: https://discord.com/channels/1006908336991645757/1006909211919274096/1362557918938923219
=> fix: error in loot drop due trying to switcheroo on WeakTableRef

scripts/skills/perks/perk_rf_steady_brace.nut
From 0.2 to 0.1 and from 20 to 10 respectively.
For a tier 1 perk this results in roughly 6 more HP damage through armor on body shots and 9 more HP damage on head shots from crossbows compared to without the perk. For Handgonnes the +10% chance to hit is quite impactful as it applies to all their targets.
=> balance: reduce armor pen and hitchance on steady brace

mod_reforged/hooks/config/character.nut, mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/effects/bleeding_effect.nut, mod_reforged/hooks/skills/effects/hyena_potion_effect.nut, mod_reforged/hooks/skills/perks/perk_hold_out.nut, mod_reforged/hooks/skills/traits/bleeder_trait.nut
- Add new character property `RF_BleedingEffectMult` that is a multiplier for damage from bleeding and maluses from bleeding. This includes the threshold for the number of stacks received in a single turn to trigger a morale check (by default 3).
- Move the effects of Bleeder Trait and Hyena Potion into their respective files using this property.
- Resilient perk now multiplies this property by 0.5 i.e. the character receives half damage and half malus from bleeding and requires double the number of stacks for a morale check.
- Similarly, Bleeder now receives a morale check even upon receiving a single Bleed (floor(3 * 0.5) = 1). And Hyena Potion doubles it to 6. Someone with Bleeder + Resilient arrives at the base 3 stacks for morale check. Someone with Hyena Potion + Resilient will get …
=> Bleeding improvements and resilient perk

mod_reforged/hooks/factions/faction.nut
Vanilla decided to not display all factions at all times in your relation screen. Probably because that would be too much scrolling.
Civilian factions (every non-military settlement comes with its own one) are hidden, if you have exactly 50 relation with them (which is the default/neutral)
In some situations however this can be confusing:
- If you completed a contract with a settlement that you previously had 40 relation with, it will now bow at 50 relation and no longer show up in the relation screen. When to try to see how that contract impacted your relation you wont be able to see it
- Same it true for when one of your actions reduced the relation of a settlement down to exactly 50
With this change neutral village factions now always show in the relation ship screen if their relation …
=> refactor: show neutral towns in relation screen with recent changes

scripts/skills/racial/rf_zombie_racial.nut
Zombie have an undocumented ability, build in their `zombie.nut` script (therefor affecting everything inheriting this), which causes 
- any humans and any player characters slain (last hitted) by them to resurrect in 2 - 3 turns
- this only affects those that actually can be resurrected
- struck down players wont resurrect
- headless characters will also not resurrect this way
This PR will mention this effect in the zombie_racial. Although it might happen that at some point an enemy receives the `zombie_racial`, but isnt inheriting from `zombie.nut`. Then we have to revisit this built-in effect
Here the tooltip how it looks now (after first adjustment)
=> refactor: mention zombie ability to resurrect slain humans as zombies

mod_reforged/hooks/states/tactical_state.nut
- Prevents cheese of reloading autosaves in hopes for better terrain
- Prevents fleeing from battle when terrain is bad (mostly against hill locations)
- Introduces more realism/persistance into the world. Terrain doesnt magically change from one moment to the next
- Introduces option to scout location before sending everyone inside
- The option to scout locations might become required and unfun busywork if you want to play optimal
- Can screenshot starting area to then 
- position full squad perfectly in the real fight
- visit the location much later into the campaign
- In some rare situation a location might come with an unbeatably hard terrain, bricking it effectively
All-in-All I'm all for trying this out.
Maybe we can discourage the need for scouting a location with other means down …
=> feat: use fixed seed for location terrain

scripts/skills/effects/rf_covering_ally_effect.nut
Currently you can unequip your shield or have it break and keep the buff on yourself and your ally.
This change fixes that. 
Swapping shields is also not allowed
=> fix: covering ally persisting even after shield is unequipped

scripts/skills/actives/rf_between_the_eyes_skill.nut, scripts/skills/actives/rf_deep_impact_skill.nut
The MSU-added DamageType for skills is never meant or expected to be null. Setting it to null creates issues within other perks or skills which try to access the damage type of skills, never expecting it to return null.
Related bug report on Discord: https://discord.com/channels/1006908336991645757/1283857645492502549/1366492777369702512
=> fix: damage type becoming null for between the eyes and deep impact

mod_reforged/hooks/entity/tactical/player.nut, mod_reforged/hooks/misc.nut
- Expand the array at least 1 level above the current character's level so that the player.getXPForNextLevel function works properly.
- Expand the array as necessary upon loading a saved game or spawning a player with a high enough level.
=> fix: expansion of the vanilla LevelXP array

mod_reforged/hooks/ai/tactical/behaviors/ai_switchto_ranged.nut
Because it is a bad idea to lose your Reach when melee opponents can move to you and attack you.
I tested this in game and it works nicely. Enemies that ended their turn in a spot where I could reach them in 1 turn didn't swap to throwing weapons, but enemies which stayed behind them swapped properly.
=> feat: prevent ai from swapping to ranged when near melee opponents

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_ghostlike.nut
Currently, Ghostlike allows you to enter the ZoC of an enemy and simply get a huge damage boost on your first attack. This doesn't seem good. This PR makes it so that you only get the buff when entering the ZoC of an enemy who is surrounded i.e. is in the ZoC of at least one other enemy. This will also now interact with perks that change the surrounding count of a character e.g. Phalanx which ignores the surrounding from x enemies, and I think that is neat.
=> balance: require surrounded enemy for ghostlike damage buff on movement

scripts/skills/perks/perk_rf_unstoppable.nut
Because the IsStunned and IsRooted properties are set during `onUpdate` of the effects that cause them, SkillOrder becomes important if we are checking for those properties in `onUpdate`. The stunned_effect may be present but if it updates after this perk then we won't detect the character being stunned. We can't check for `CurrentProperties.IsStunned` either because CurrentProperties are only updated at the end of the entire update cycle and if the stun comes from an effect that updates after this perk, we will still miss it.
However, this will now cause the things done by this perk to happen a bit too late for other skills which may depend on those stats (e.g. increased Initiative). But that seems correct because otherwise that also depends on SkillOrder which seems wrong from a design …
=> fix: unstoppable not resetting to 0 upon getting stunned or rooted

mod_reforged/hooks/experimental_modules/onSpawnEntity.nut
When combat is started it calls onCombatStarted for all the actors. This triggers a skill_container.update(). This leads to the first actor calling his RF_onSpawn which then calls onActorSpawned on all the other actors, leading to them triggering a skill_container.update() which then triggers their own RF_onSpawn which triggers it for all others leading to the stack getting bigger and bigger. At a certain number of entities this can lead to stack overflow.
We now block the other actor from triggering his RF_onSpawn due to the update from his onActorSpawned event. This means that every actor gets his RF_onSpawn due to the original onCombatStarted call, leading to a sensible stack.
=> fix: potential stack overflow due to RF_onSpawn

README.md, mod_reforged/auto_pilot_fixes.nut, scripts/skills/perks/perk_rf_flail_spinner.nut, scripts/skills/perks/perk_rf_whirling_death.nut
This PR includes the fixes of [AutoPilot New](https://github.com/Suor/battle-brothers-mods/tree/master/autopilot) into Reforged. This should help prevent AI related crashes caused by delayed kills, and it also includes some other fixes.
Thanks to this inclusion, this PR also adjusts Flail Spinner and Whirling Death to be lethal again.
The mod's ReadMe file is also updated to mention that Reforged uses code from this AutoPilot New (this is required by the BSD license).
=> feat: include autopilot fixes into Reforged

scripts/skills/actives/rf_flaming_arrows_skill.nut
People say the skill is extremely difficult to use now and very costly due to the 2 ammo consumption, therefore, people just use more Quick Shots instead.
- Reduce RangeModifier from -2 to -1
- Remove the consumption of 2 ammo per shot.
- Remove the base -10% chance to hit.
- Remove the +10% direct damage.
=> balance: buff flaming arrows range, accuracy and ammo consumption

mod_reforged/hooks/scenarios/world/militia_scenario.nut
Militia perk group has Phalanx at tier 1 but Shield perk group has it at tier 2, so during the Militia Origin which guarantees the Militia Perk Group on all characters, if the character already rolled the Shield perk group he'd have Phalanx at tier 2.
=> fix: militia origin getting phalanx perk at tier 2 instead of 1

mod_reforged/hooks/entity/tactical/enemies/goblin_wolfrider.nut, mod_reforged/hooks/skills/actives/wolf_bite.nut
For "balancing" them we add Fast Adaptation and Double Strike perks to them.
=> fix(vanilla): goblin wolfriders getting damage modified by wolf bite

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_bulwark.nut
The flat Resolve bonus is too high and some players have given the feedback that it is too much of a stat boost. It also competes this way with Fortified Mind. Another egregious use case is putting it on a Bannerman in heavy armor for a large boost to Resolve. Changing it to affect Resolve only during morale checks keeps the perk strong for its purpose while resolving the issues around it and giving it more of a unique identity.
=> balance: apply bulwark bonus only during morale checks

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/entity/tactical/goblin.nut, mod_reforged/hooks/skills/actives/throw_net.nut, scripts/skills/perks/perk_rf_angler.nut, scripts/skills/racial/rf_goblin_racial.nut
- Increase the AP cost of Throw Net from 4 to 5 and reduce the MaxRange from 3 to 2.
- Goblins can still throw at a range of 3 tiles. This is achieved by adding a new rf_goblin_racial skill.
- Angler perk now increases the range by 1 tile and only applies its 50% increased AP cost of Break Free when throwing the net at a distance of 2 or fewer tiles.
Nets are extremely powerful and are a bit too easy/flexible to use to eliminate high threat targets. This PR nerfs them by not modifying their efficacy, but making them harder to use i.e. they are now more challenging to pull off. At the same time the player has options via perks to get back to the original strength for dedicated utility net bros.
| Situation | Old | New |
| ---- | ---- | ---- |
| Net in bag | Swap to net (4), throw (4) and …
=> feat: nerf throwing net range and AP cost and adjust angler and goblins

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/perks/perk_mastery_spear.nut
There was some [feedback](https://discord.com/channels/1006908336991645757/1296562347066003560/1373412867444838513) on Discord about this. This change further reins in the 2h spears, still giving them the free attack but in a more restricted way than before.
=> balance: disable free attack from spear mastery on 2h spears upon moving

scripts/skills/perks/perk_rf_vigorous_assault.nut
Whereas the expected behavior is that it should drop the AP cost down to a minimum of 1.
=> fix: vigorous assault not applying ap reduction if it would drop it <=0

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_battle_fervor.nut, unpacked_brushes/rf_ui/metadata.xml
As long as you start each turn at Confident morale. Each stack increases attributes by 5%. Can have a maximum of 4 stacks. Expires upon losing Confident morale.
=> feat: rework battle fervor to gain stack at turn start with morale check

mod_reforged/hooks/experimental_modules/onAnySkillExecutedFully.nut
- Don't count scheduleEvent with `::TimeUnit.Rounds` as part of skill execution.
- Delayed events are only considered part of a skill execution if they are called from a function with the skill as the env variable (i.e. inside the skill script or a helper function with that skill as the env).
- Prevent the AI from executing a skill while another skill has delayed events (just like the player). Otherwise the AI overwrites the scheduled skill object and this causes the callback wrapper to throw an error.
=> onAnySkillExecuted various fixes 

mod_reforged/hooks/experimental_modules/onAnySkillExecutedFully.nut, mod_reforged/msu_systems/mod_settings.nut, scripts/!mods_preload/mod_reforged.nut
This should improve AI performance because we allow the AI to evaluate (but not execute) its behaviors while delayed events are scheduled from a used skill. However, if anything important changed in the state during the delayed events e.g. anyone died, or moved, or morale state changed, or Action Points changed, then we force the AI to reevaluate using this new state. This is because any important state change could make the already evaluated behaviors to be no longer valid for execution.
=> feat: allow the AI to evaluate in parallel but rethink if state changed

mod_reforged/hooks/experimental_modules/onAnySkillExecutedFully.nut
- When preventing skill execution, instead of checking for `ScheduleSkills.len()` we simply check for any scheduled event with `VirtualTime` or if the `Navigator.IsTravelling`. The former is true for delayed skill effects and the latter is true for `teleport` and `switchEntities`.
- Extracted the logic of allowing skill execution into a separate function. 
- We only consider events scheduled with `TimeUnit.Virtual` as delayed skill effects because this is the only time unit that makes sense to be used for delayed skill effects. This is also in line with what vanilla checks in `turn_sequence_bar.initNextTurn`. It also cleans up the code a bit.
- Improved debugging logs by printing caller ClassName and function name, along with file source and line and callback function name.
=> onAnySkillExecutedFully improvements for stability and better debugging

mod_reforged/hooks/items/weapons/greenskins/goblin_pike.nut
This weapon has lower AP cost so this is gameplay-wise a better balance. It is also thematic for the goblin pike to be smaller than a human one.
=> balance: reduce goblin pike reach from 7 to 6

mod_reforged/hooks/skills/actives/cascade_skill.nut, mod_reforged/hooks/skills/actives/hail_skill.nut
- Fix not rolling thrice if any roll succeeded.
- Fix not accounting for defense reroll chance on target.
- Fix not accounting for modifications to roll from Beginner difficulty.
- Rewrite the skills to no longer set IsUsingHitChance to false. Instead use Modular Vanilla functionality to check for successful hits, print the attack log with all 3 rolls and adjust the roll in the actual attack to guarantee hit or miss.
=> fix: cascade and hail rolling inaccuracies

mod_reforged/hooks/entity/world/location.nut
Add brief explanation of onAfterInit limitations
This finally fixes a leftover bug from this PR: https://github.com/Battle-Modders/mod-reforged/pull/189
=> fix: non-settlement banner not receiving any banner offset after loading

mod_reforged/hooks/skills/actives/disarm_skill.nut
Possible patch note for Reforged:
- Remove misleading damage type line from disarm skill tooltip
=> fix(vanilla): remove redundant injury definitions from disarm skill
