mod_reforged/config/config.nut, mod_reforged/config/math/math.nut, mod_reforged/hooks/skills/backgrounds/character_background.nut
I briefly tested this ingame and on the first town it worked fine.
=> feat: randomize hiring cost of brothers between +-20%

mod_reforged/hooks/skills/backgrounds/swordmaster_background.nut
Check my code it may very well be wrong.
=> refactor: exclude asthmatic and cocky traits and ranged defense talent

mod_reforged/hooks/skills/backgrounds/gladiator_background.nut, mod_reforged/hooks/skills/backgrounds/hedge_knight_background.nut, mod_reforged/hooks/skills/backgrounds/sellsword_background.nut, mod_reforged/hooks/skills/backgrounds/swordmaster_background.nut
Removed from the following backgrounds and added as a 10% chance: Gladiator, Hedge Knight, Sellsword, Swordmaster
=> refactor(balance): remove professional guarantee and add as chance

mod_reforged/hooks/entity/tactical/human.nut, scripts/mods/mod_reforged/perk_groups/pg_rf_power.nut, scripts/mods/mod_reforged/perk_groups/pg_rf_shield.nut, scripts/mods/mod_reforged/perk_groups/pg_rf_sturdy.nut
We currently add Recover as a perk on many enemies, that's ok. We don't have to change that in this PR imo.
=> feat: add recover skill on every human and remove perk from perk groups

scripts/mods/mod_reforged/perk_groups/pg_rf_light_armor.nut, scripts/mods/mod_reforged/perk_groups/pg_rf_medium_armor.nut
=> refactor: switch dodge perk tier with the perk below it

mod_reforged/hooks/items/accessory/iron_will_potion_item.nut, mod_reforged/hooks/skills/effects/iron_will_effect.nut
=> refactor: improve vanilla iron will tooltip to clarify full immunity

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_phalanx.nut
Don't lose shieldwall with phalanx if adjacent ally has shieldwall
=> Rework phalanx dont lose shieldwall

mod_reforged/hooks/skills/traits/tiny_trait.nut
To be in line with the Huge trait which grants +1 Reach.
=> refactor: grant -1 reach with tiny trait

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_bloodlust.nut
- Require cleaver
- Gain increased Resolve, Initiative and Fatigue Cost reduction after fatalities
=> refactor: rework bloodlust

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_strength_in_numbers.nut
- Gain resolve for adjacent allies instead of allies in combat
- Work with allied actors instead of faction only actors
=> Refactor tweak strength in numbers

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_feral_rage.nut
- Remove status resistances
- Increase rage generation and lower loss rate
- Slightly adjust the values of the bonuses gained from rage
=> refactor: rework feral rage

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_professional.nut
Grant the first two perks in a random melee perk group that this character has access to.
=> refactor: rework professional gain perks from a random melee perk group

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/perks/perk_mastery_throwing.nut, scripts/skills/perks/perk_rf_hybridization.nut
- Move melee skill based hit chance bonus from throwing mastery to Hybridization
- Move damage type based effect application from Hybridization to Throwing Mastery
- Remove increased damage to shields from Throwing Spear from Hybridization
=> refactor: rework throwing mastery and hybridization

mod_reforged/config/z_nested_tooltips.nut, mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_unstoppable.nut
As long as you continue to end your turn with half or less AP remaining.
=> refactor: rework unstoppable to increase AP and Initiative

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_weapon_master.nut
Give tier corresponding perks for equipped weapon based on what perks you have unlocked
=> refactor: rework weapon master to give tier corresponding perks

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/msu.nut, mod_reforged/hooks/skills/actives/taunt.nut, mod_reforged/hooks/skills/effects/taunted_effect.nut
I tested this ingame. It seems to work correctly.
**Screenshots:**
=> Refactor rework taunt effect

scripts/skills/effects/rf_encumbrance_effect.nut
This PR is purely style and does not change how the effect works ingame.
It will make it easier for us change and swap values around as we only need to adjust them in one place now.
This will also make it much easier for submods to adjust the effects of the different levels.
=> refactor: improve structure and moddability of encumbrance_effect

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/perks/perk_fearsome.nut
=> refactor: remove cap and handicap from fearsome's calculation

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_offhand_training.nut, scripts/skills/perks/perk_rf_target_practice.nut
- Require bow
- Remove ability to swap ammo for free
- Change bonus to affect enemies not in cover instead of enemies with no adjacent ally
=> refactor: rework target practice

mod_reforged/hooks/entity/tactical/enemies/skeleton_boss.nut, mod_reforged/hooks/entity/tactical/enemies/skeleton_heavy.nut, mod_reforged/hooks/entity/tactical/enemies/skeleton_heavy_bodyguard.nut, mod_reforged/hooks/entity/tactical/enemies/skeleton_heavy_polearm.nut, mod_reforged/hooks/entity/tactical/enemies/skeleton_light.nut, mod_reforged/hooks/entity/tactical/enemies/skeleton_medium.nut, mod_reforged/hooks/entity/tactical/enemies/skeleton_medium_polearm.nut, mod_reforged/hooks/entity/tactical/enemies/skeleton_priest.nut, scripts/entity/tactical/enemies/rf_skeleton_heavy_lesser.nut, scripts/entity/tactical/enemies/rf_skeleton_heavy_lesser_bodyguard.nut, scripts/entity/tactical/enemies/rf_skeleton_light_elite.nut, scripts/entity/tactical/enemies/rf_skeleton_light_elite_polearm.nut, scripts/entity/tactical/enemies/rf_skeleton_medium_elite.nut, scripts/entity/tactical/enemies/rf_skeleton_medium_elite_polearm.nut
Per Darxo's request, which I agree with.
=> docs: add entity names as comments to skeleton files

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/actives/adrenaline_skill.nut, mod_reforged/hooks/skills/effects/adrenaline_effect.nut
I tested this ingame and it seems to work
=> refactor: buff adrenaline effect to ignore effects of injuries

mod_reforged/hooks/items/weapons/ancient/crypt_cleaver.nut, mod_reforged/hooks/items/weapons/barbarians/rusty_warblade.nut, mod_reforged/hooks/items/weapons/barbarians/skull_hammer.nut, mod_reforged/hooks/items/weapons/bardiche.nut, mod_reforged/hooks/items/weapons/falchion.nut, mod_reforged/hooks/items/weapons/longsword.nut, mod_reforged/hooks/items/weapons/military_cleaver.nut, mod_reforged/hooks/items/weapons/two_handed_hammer.nut, mod_reforged/hooks/items/weapons/two_handed_wooden_hammer.nut, scripts/items/weapons/named/named_rf_battle_axe.nut, scripts/items/weapons/rf_battle_axe.nut, scripts/items/weapons/rf_estoc.nut, scripts/items/weapons/rf_great_khopesh.nut, scripts/items/weapons/rf_kriegsmesser.nut, scripts/items/weapons/rf_poleflail.nut, scripts/items/weapons/rf_reinforced_wooden_poleflail.nut, scripts/skills/actives/rf_flail_pole_skill.nut, scripts/skills/actives/rf_lash_pole_skill.nut
See each individual commit message for the changes.
=> Refactor weapons rebalance

mod_reforged/hooks/skills/actives/reload_bolt.nut, mod_reforged/hooks/skills/actives/reload_handgonne_skill.nut
This will fix issues where new skills like Cheap Trick are put before Reload
=> refactor: move reload skills slightly forward in SkillOrder

mod_reforged/hooks/scenarios/world/lone_wolf_scenario.nut
I think Lone Wolf should start with greatsword instead of longsword, as it fits the theme of the origin and character more, and also is more in line with how vanilla lone wolf is intended to be
=> Lone wolf greatsword

mod_reforged/hooks/entity/world/settlement.nut
without a kennel being attached
=> feat: allow wardogs and warhounds to rarely spawn in marketplaces

mod_reforged/hooks/skills/actives/hand_to_hand.nut
As suggested 3 months ago and liked by both of you, this is the hand to hand buff.
=> refactor: remove 10% hitchance penalty for hand to hand combat

scripts/skills/perks/perk_rf_offhand_training.nut
For example when using a skill which removes/unequips the item upon use e.g. Throw Net.
=> fix: offhand training not always consuming the free use

mod_reforged/hooks/entity/tactical/enemies/zombie.nut, mod_reforged/hooks/entity/tactical/enemies/zombie_knight.nut, mod_reforged/hooks/entity/tactical/enemies/zombie_yeoman.nut, scripts/skills/racial/rf_zombie_racial.nut
The main intention of this change is to show those properties to the player.
=> refactor: move several zombie properties into new rf_zombie_racial skill

mod_reforged/hooks/entity/tactical/enemies/ghost_knight.nut
Otherwise known as the Rachegeist.
=> refactor: remove anticipation from ghost knight

mod_reforged/config/config.nut, mod_reforged/hooks/skills/backgrounds/character_background.nut
This reverts commit dd71b1193637d13a0a91661a98e20ec02150491e.
=> revert: "feat: randomize hiring cost of brothers between +-20%"

mod_reforged/hooks/skills/actives/cascade_skill.nut, mod_reforged/hooks/skills/actives/hail_skill.nut
- Cascade from 13 to 15
- Hail from 25 to 30
=> refactor: increase fatigue cost of three headed flail skills

mod_reforged/hooks/config/character.nut, mod_reforged/hooks/ui/screens/tooltip/tooltip_events.nut, ui/mods/mod_reforged/js_hooks/screens/character/modules/character_screen_left_panel/character_screen_stats_module.js
=> Feat display base attributes

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/actives/throw_smoke_bomb_skill.nut, mod_reforged/hooks/skills/racial/champion_racial.nut, scripts/skills/actives/rf_blitzkrieg_skill.nut, scripts/skills/actives/rf_encourage_skill.nut, scripts/skills/actives/rf_gain_ground_skill.nut, scripts/skills/actives/rf_hold_steady_skill.nut, scripts/skills/actives/rf_net_pull_skill.nut, scripts/skills/actives/rf_onslaught_skill.nut, scripts/skills/actives/rf_swordmaster_charge_skill.nut, scripts/skills/actives/rf_swordmaster_stance_half_swording_skill.nut, scripts/skills/actives/rf_swordmaster_tackle_skill.nut, scripts/skills/effects/rf_hooked_shield_effect.nut, scripts/skills/effects/rf_onslaught_effect.nut, scripts/skills/perks/perk_rf_strength_in_numbers.nut
I've made a large number of small changes during my work updating the dev sheet that I think improve readability and style. Comment where you disagree with my changes please.
=> refactor: string, description and tooltip improvements

mod_reforged/hooks/entity/tactical/humans/noble_sergeant.nut, scripts/ai/tactical/agents/rf_military_sergeant_agent.nut, scripts/entity/tactical/humans/rf_marshal.nut
This causes Sergeants and Marshals to prefer to Wait during the first round, so that they don't barge forward like idiots before their infantry has had a chance to mobilize first.
=> refactor: add new agent for sergeants to prefer wait during first round

mod_reforged/hooks/config/faction_bandits.nut, mod_reforged/hooks/config/faction_barbarians.nut, mod_reforged/hooks/config/faction_beasts.nut, mod_reforged/hooks/config/faction_civilian.nut, mod_reforged/hooks/config/faction_greenskins.nut, mod_reforged/hooks/config/faction_military.nut, mod_reforged/hooks/config/faction_southern.nut, mod_reforged/hooks/config/faction_undead.nut
bandits
barbarians
beasts
civilians
military
southern
undead
comment vanilla values
=> refactor: include full attributes table for all enemies

mod_reforged/hooks/skills/actives/throw_spear_skill.nut
Now always hits shield if target has shield (just like it used to) and inflicts damage to the shield (vanilla default is 26 damage) and inflicts 40 Fatigue (Reforged mechanic).
=> refactor: allow throw spear to target shield and inflict fatigue

mod_reforged/hooks/ui/global/data_helper.nut, ui/mods/mod_reforged/generic.css, ui/mods/mod_reforged/js_hooks/screens/character/modules/character_screen_left_panel/character_screen_perks_module.js, ui/mods/mod_reforged/js_hooks/screens/world/modules/world_town_screen/world_town_screen_hire_dialog_module.js
- Add perk group screen to character perks screen
- Add switch button to hire screen tryout module
=> feat: improve UX for viewing perk groups of characters

mod_reforged/hooks/config/spawnlist_master.nut, scripts/mods/mod_reforged/dynamic_spawns/parties/nomad_parties.nut
reduce strength and cost of nomad outlaw
set startingresourcemin of nomad leader to 250
=> balance: adjust nomad spawns

scripts/skills/perks/perk_rf_weapon_master.nut
With this setup for 2-way hybrid weapons if you have a perk from one of the weapon types' perk groups you get the perk from the other weapon type's perk group - instead of the alphabetically first one. However, if you have a perk from a perk group other than this weapon's weapon types, then you get the perks from this weapon's alphabetically first weapon type's perk group.
The solution isn't so pretty to look at in code - but it seems to work. An alternative approach is to iterate over all weapon perk groups in one go and then check if this item also has that weapon type that belongs to that perk group but that isn't necessarily going to be beautiful either as we have to somehow translate perk groups to weapon types which isn't always 1:1 (e.g. crossbow perk group applies to two weapon …
=> refactor: improve weapon master for hybrid weapons

mod_reforged/hooks/items/weapons/greatsword.nut, mod_reforged/hooks/items/weapons/longsword.nut, scripts/items/weapons/rf_greatsword.nut, scripts/items/weapons/rf_kriegsmesser.nut, scripts/items/weapons/rf_two_handed_falchion.nut
Based on comparisons with other 2h swords, 2h weapons, and all cleavers.
=> balance: change weight of two handed falchion and kriegsmesser

mod_reforged/hooks/entity/tactical/enemies/bandit_raider.nut, mod_reforged/hooks/entity/tactical/enemies/bandit_thug.nut, mod_reforged/hooks/entity/tactical/enemies/goblin_fighter.nut, mod_reforged/hooks/entity/tactical/goblin.nut, mod_reforged/hooks/skills/backgrounds/militia_background.nut, scripts/entity/tactical/enemies/rf_bandit_scoundrel.nut, scripts/entity/tactical/enemies/rf_bandit_vandal.nut
2h weapon changes to bandits as discussed
=> Bandits and goblins minor rebalance

mod_reforged/hooks/config/spawnlist_master.nut, scripts/mods/mod_reforged/dynamic_spawns/parties/bandit_parties.nut, scripts/mods/mod_reforged/dynamic_spawns/units/bandit_units.nut
Reduce costs
Tier 2: 18 to 16
Tier 3: 25 to 22
Tier 4: 30 to 26
Delay tough bandit spawns a bit
For bandits to upgrade a bit quicker
=> Lower costs of certain bandit units and delay tough bandit spawns

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/perks/perk_nimble.nut, scripts/skills/perks/perk_rf_poise.nut
Nimble is at 15% while Poise is at 35% of base fatigue including the effects of traits and permanent injuries.
=> refactor: scale nimble and poise stamina modifier threshold

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/effects/lone_wolf_effect.nut
Also rewrite the perk code to make it more modular by adding a member field for the bonus mult and a new function for checking validity of the actor's position.
=> refactor: rework lone wolf to <=1 ally within 2 tiles and none adjacent

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/perks/perk_nimble.nut, scripts/skills/perks/perk_rf_poise.nut
I briefly tested the Nimble threshold with a guy who had 92 Stamina. But I don't know if that was sufficient. I didn't have one available with 90 or less.
I have **not** tested whether the Poise threshold works accordingly.
=> refactor: introduce minimum thresholds for nimble and poise

scripts/skills/special/rf_polearm_adjacency.nut
=> balance: disable ally adjacency malus from crowded effect

mod_reforged/hooks/config/strings.nut, scripts/skills/effects/rf_retribution_effect.nut
I tested this ingame and it looks to work correctly.
Description of the perk is also adjusted.
=> refactor: implement maximum stacksize of 1 for retribution

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_phalanx.nut
I tested this ingame and the descriptions and effect seem to work correctly
Here the tooltip line spawned on **Shieldwall**
=> refactor: replace perma shieldwall on phalanx with shieldwall discount

mod_reforged/hooks/entity/tactical/enemies/bandit_marksman.nut, mod_reforged/hooks/entity/tactical/enemies/goblin_ambusher.nut, mod_reforged/hooks/entity/tactical/humans/noble_arbalester.nut, scripts/entity/tactical/enemies/rf_bandit_hunter.nut, scripts/entity/tactical/enemies/rf_bandit_sharpshooter.nut, scripts/entity/tactical/humans/rf_arbalester_heavy.nut
Will hopefully fix ranged enemy ai charging ahead and getting caught
=> balance: manually set vision of most ranged enemies to 8 like vanilla

mod_reforged/hooks/skills/effects/net_effect.nut
Because in Reforged being netted reduces Reach as well.
=> balance: reduce melee defense malus of net from vanilla 45% to 25%

mod_reforged/hooks/skills/backgrounds/gladiator_background.nut, mod_reforged/hooks/skills/backgrounds/old_gladiator_background.nut
- Gladiators start with a random 5-15 battles already under their belt and the Arena Fighter or Arena Veteran trait as applicable.
- Old Gladiator starts with 15-25 battles and the Arena Veteran trait.
=> feat: add arena traits to gladiator and old gladiator backgrounds

mod_reforged/hooks/skills/actives/shieldwall.nut, mod_reforged/hooks/skills/effects/shieldwall_effect.nut, scripts/skills/perks/perk_rf_shield_sergeant.nut
Also optimize and cleanup code.
=> fix: shield sergeant losing shieldwall at turn start

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_swift_stabs.nut
=> refactor: improve moddability and require dagger and piercing attack

mod_reforged/hooks/config/strings.nut, scripts/skills/perks/perk_rf_phalanx.nut
- Require Melee Piercing Attack and either a Shield or Two-Handed Weapon.
- Gain +1 Reach per adjacent ally who fulfills these requirements.
- Ignore the surround malus from enemies up to the number of adjacent allies who fulfill these requirements.
=> refactor: rework phalanx

scripts/skills/perks/perk_rf_weapon_master.nut
So that Weapon Master works properly with perks that affect item action cost.
=> refactor: retain perks from previous weapon until new is equipped

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/skills/perks/perk_inspiring_presence.nut
Helps clarify misunderstandings like this one: https://discord.com/channels/1006908336991645757/1337779290984546407/1340105413940609054
=> refactor: clarify inspiring presence tooltip about same faction allies

scripts/!mods_preload/mod_reforged.nut
If you know any other mods that are known to be incompatible, please let me know and I'll add them to this PR.
=> feat: add some known incompatible mods to conflictsWith list

mod_reforged/hooks/scenarios/world/beast_hunters_scenario.nut, mod_reforged/hooks/scenarios/world/militia_scenario.nut, mod_reforged/hooks/scenarios/world/raiders_scenario.nut, mod_reforged/hooks/scenarios/world/rangers_scenario.nut
- Peasant Miltia: Militia perk group
- Northern Raiders: Adrenaline perk
- Band of Poachers: Pathfinder perk
- Beast Slayers: Fortified Mind perk
=> refactor: add some guaranteed perks to certain origins

scripts/skills/perks/perk_rf_vigorous_assault.nut
Instead of using distance from starting to finish tile. Also clean up and streamline the code implementation.
=> fix: use actual number of tiles traveled for vigorous assault

mod_reforged/hooks/skills/backgrounds/nomad_ranged_background.nut, mod_reforged/hooks/skills/backgrounds/poacher_background.nut
Poacher:
- Guaranteed 40% chance to have Bow and 60% chance to have Crossbow.
- Guaranteed Ranged fighting style.
- 2x multiplier for bow, crossbow and throwing perk groups.
Ranged Nomad:
- Having 2 ranged weapon perk groups is guaranteed. The first one has a 33% chance to be any of Bow, Crossbow or Throwing and then the second one has a 50% chance of being one of the remaining two.
=> Fix ranged weapons availability on poacher and nomad ranged backgrounds

mod_reforged/hooks/skills/perks/perk_battle_flow.nut
=> balance: reduce battle flow stamina recovered mult from 0.15 to 0.1

mod_reforged/hooks/config/strings.nut, mod_reforged/hooks/items/ammo/legendary/quiver_of_coated_arrows.nut, scripts/skills/perks/perk_rf_deep_cuts.nut
Are there any others that need to be updated so they are consistent with the Reforged bleeding mechanic?
=> Fix bleed related tooltips

scripts/skills/perks/perk_rf_professional.nut
=> refactor: use actor uid to seed roll for professional

mod_reforged/hooks/mods/mod_dpf/classes/perk_tree.nut, scripts/skills/perks/perk_rf_realized_potential.nut
- Roll weighted random perk groups instead of completely random when realizing potential.
- Use actor UID to seed the rolls.
=> Realized potential weighted random and seeded roll

scripts/skills/effects/rf_old_swordmaster_scenario_recruit_effect.nut, scripts/skills/perks/perk_rf_discovered_talent.nut
- Discovered Talent
- Old Swordmaster recruit effect for gaining free perks
=> Convert some perks to roll with uid

mod_reforged/hooks/ui/screens/tactical/modules/turn_sequence_bar/turn_sequence_bar.nut, mod_reforged/msu_systems/mod_settings.nut, ui/mods/mod_reforged/js_hooks/screens/tactical/modules/tactical_screen_turnsequencebar/turnsequencebar_module.js
Otherwise it has name collision with the AutoPilot New mod by Hackflow (https://www.nexusmods.com/battlebrothers/mods/675).
=> refactor: prefix wait all functions with RF_

scripts/skills/perks/perk_rf_discovered_talent.nut
- Improve moddability of the perk by extracting MaxStars into a member variable and the stars rolling chance into a function.
- Buff the chance:
| Stars | Old Chance | New Chance |
| -- | -- | -- |
| 1 | 70 | 60 |
| 2 | 20 | 25 |
| 3 | 10 | 15 |
=> Discovered talent buff

mod_reforged/hooks/skills/effects/bleeding_effect.nut
In my testing it feels good with these values.
=> feat: speed up icons for bleeds from a single skill after the first

mod_reforged/hooks/skills/backgrounds/eunuch_background.nut, mod_reforged/hooks/skills/backgrounds/flagellant_background.nut, mod_reforged/hooks/skills/backgrounds/gambler_background.nut, mod_reforged/hooks/skills/backgrounds/retired_soldier_background.nut, mod_reforged/hooks/skills/backgrounds/squire_background.nut
Eunuchs, Gambler, Historian, Retired Soldier
=> balance: adjust tactician weight on backgrounds

mod_reforged/config/math/math.nut
These are two additional values unique to a specific campaign
=> refactor: add seed and company name as additional salt for seedRandom

mod_reforged/hooks/entity/tactical/player.nut, mod_reforged/hooks/skills/backgrounds/character_background.nut
Tested and seems to work nicely.
=> feat: include effect of traits and perm injuries in projected attributes

mod_reforged/hooks/entity/tactical/enemies/trickster_god.nut, scripts/skills/actives/rf_gore_zoc_skill.nut
People say Ijirok fight is too easy. @Uberbagel suggested adding a ZoC skill to the Ijirok and it makes sense.
=> feat: add zoc skill for ijirok

mod_reforged/hooks/experimental_modules/onAnySkillExecutedFully.nut, scripts/skills/effects/rf_cheap_trick_effect.nut, scripts/skills/effects/rf_retribution_effect.nut, scripts/skills/effects/rf_take_aim_effect.nut, scripts/skills/perks/perk_rf_combo.nut, scripts/skills/perks/perk_rf_retribution.nut, scripts/skills/perks/perk_rf_sweeping_strikes.nut, scripts/skills/perks/perk_rf_swift_stabs.nut
This PR also converts several relevant skills to use onAnySkillExecutedFully.
=> feat: add onAnySkillExecutedFully experimental module

mod_reforged/hooks/config/faction_barbarians.nut, mod_reforged/hooks/config/faction_military.nut, mod_reforged/hooks/entity/tactical/enemies/sand_golem.nut, mod_reforged/hooks/entity/tactical/humans/barbarian_madman.nut, mod_reforged/hooks/entity/tactical/humans/caravan_guard.nut, mod_reforged/hooks/entity/tactical/humans/knight.nut, mod_reforged/hooks/entity/tactical/humans/noble_footman.nut, mod_reforged/hooks/entity/tactical/humans/noble_sergeant.nut, scripts/entity/tactical/enemies/rf_bandit_marauder.nut, scripts/entity/tactical/humans/rf_footman_heavy.nut, scripts/entity/tactical/humans/rf_knight_anointed.nut, scripts/entity/tactical/humans/rf_marshal.nut
Must be merged after Uber Misc Fixes
=> Uber balance

mod_reforged/hooks/entity/tactical/humans/desert_devil.nut, mod_reforged/hooks/entity/tactical/humans/hedge_knight.nut, scripts/entity/tactical/humans/rf_man_at_arms.nut
Named Poleaxe
- Hedge Knight champion
- Man At Arms champion Named Voulge
- Bladedancer champion
=> refactor: add named poleaxe and named voulge to enemies
